//! `provider.norbelys.provision`: creates a `norbelys` connection's login on the managed MTA
//! through its control API, and registers where the MTA posts the login's evidence.
//!
//! # The control API
//!
//! The MTA's control service listens on the private network. Every request is signed per
//! Standard Webhooks (<https://www.standardwebhooks.com/>) with the per-installation secret
//! (`MTA_CONTROL_SECRET`, `whsec_` and the base64 of 24 to 64 bytes): `webhook-id` (fresh for
//! every request, retries included, since the service accepts an id once), `webhook-timestamp`
//! (Unix seconds) and `webhook-signature` (`v1,` and the base64 HMAC-SHA256 of
//! `id.timestamp.body`). Redirects are never followed, nothing is retried inside a call, and
//! errors come back as problem documents whose `detail` is shown on the connection.
//!
//! # The job
//!
//! 1. Read the connection (a `norbelys` connection in `verifying`) and its provider webhook.
//! 2. The login: when the MTA knows the address, a new password is issued for it; otherwise it is
//!    created (`kind` service for a domain, mailbox for a separate inbox; `rate_class` customer),
//!    which the MTA refuses unless the
//!    address's domain is registered and verified there. Either way the password is answered
//!    once and never stored by the MTA.
//! 3. The route: `PUT /v1/routes/{provider webhook}` with the webhook's URL, its Standard
//!    Webhooks secret (generated by Norbelys when the connection was created) and the login, so
//!    the MTA's evidence for this login arrives signed at this connection's webhook.
//! 4. Under the fence (the connection's credential version and status unchanged), the password
//!    is sealed through `set_connection_credential()`. A separate SMTP/IMAP check makes the
//!    connection active after the MTA has loaded the credential; API acceptance alone is not readiness.
//!
//! Every step can run again: a login that exists gets a new password (the one a lost answer
//! carried is replaced), and a route is replaced whole. So the kind is retried after a failure
//! like any external, repeatable call. A refusal the person must fix (the domain is not verified
//! on the MTA, the webhook URL is not one the MTA posts to) moves the connection to `failed` with
//! the MTA's words; `verify` runs the job again.

use std::time::Duration;

use reqwest::{Method, StatusCode};
use secrecy::{ExposeSecret as _, SecretString};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use url::Url;

use super::check::ConnectionCheck;
use super::credentials::{self, Credential};
use super::{Env, SettingsError, health};
use crate::crypto::{self, Keys};
use crate::domain::ids::{Connection, Id, ProviderWebhook};
use crate::domain::senders::{HealthEvent, Status};
use crate::domain::time::Timestamp;
use crate::jobs::{self, Effect, Job, JobContext, JobError, Outcome, Queue};

/// The longest one control request may take.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(15);
/// How long connecting to the control service may take.
const CONNECT_TIMEOUT: Duration = Duration::from_secs(5);
/// The largest answer read.
const ANSWER_LIMIT: usize = 64 * 1024;

/// The managed MTA's control API.
#[derive(Clone)]
pub struct Control {
    client: reqwest::Client,
    base: Url,
    secret: Vec<u8>,
}

impl std::fmt::Debug for Control {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Control")
            .field("base", &self.base.as_str())
            .finish_non_exhaustive()
    }
}

/// Why a control request gave no usable answer.
#[derive(Debug, thiserror::Error)]
pub enum ControlError {
    /// No answer: the service could not be reached, or it timed out.
    #[error("the managed MTA's control API did not answer: {0}")]
    Network(String),
    /// An answer outside the contract.
    #[error("the managed MTA's control API answered {status}: {detail}")]
    Answer { status: u16, detail: String },
}

impl Control {
    /// The client of the control API at `base`, signing with `secret` (`whsec_…`).
    ///
    /// # Errors
    ///
    /// The secret is not `whsec_` and the base64 of 24 to 64 bytes, or the HTTP client cannot
    /// be built.
    pub fn new(
        base: Url,
        secret: &SecretString,
        private_transport: bool,
    ) -> Result<Self, SettingsError> {
        let loopback = base.host_str() == Some("localhost")
            || base.host_str().is_some_and(|host| {
                host.trim_matches(['[', ']'])
                    .parse::<std::net::IpAddr>()
                    .is_ok_and(|ip| ip.is_loopback())
            });
        let private = base.host_str().is_some_and(|host| {
            host.trim_matches(['[', ']'])
                .parse::<std::net::IpAddr>()
                .is_ok_and(|ip| match ip {
                    std::net::IpAddr::V4(ip) => ip.is_private(),
                    std::net::IpAddr::V6(ip) => ip.is_unique_local(),
                })
        });
        if base.host().is_none()
            || !base.username().is_empty()
            || base.password().is_some()
            || base.fragment().is_some()
            || base.query().is_some()
            || !(base.scheme() == "https"
                || (base.scheme() == "http" && (loopback || (private_transport && private))))
        {
            return Err(SettingsError::Invalid("MTA control requires HTTPS, loopback, or an explicitly authorized private tunnel IP".into()));
        }
        let secret = crate::webhooks::deliver::secret_bytes(secret.expose_secret().trim())
            .filter(|bytes| (24..=64).contains(&bytes.len()))
            .ok_or_else(|| {
                SettingsError::Invalid(
                    "MTA_CONTROL_SECRET is `whsec_` and the base64 of 24 to 64 bytes".to_owned(),
                )
            })?;
        let client = reqwest::Client::builder()
            .redirect(reqwest::redirect::Policy::none())
            .no_proxy()
            .timeout(REQUEST_TIMEOUT)
            .connect_timeout(CONNECT_TIMEOUT)
            .user_agent(concat!("Norbelys/", env!("CARGO_PKG_VERSION")))
            .build()
            .map_err(|error| SettingsError::Invalid(format!("the control client: {error}")))?;
        Ok(Self {
            client,
            base,
            secret,
        })
    }

    /// One signed request; the answer's status and JSON body (`null` when empty).
    ///
    /// # Errors
    ///
    /// No answer, or an answer that is not JSON.
    async fn call(
        &self,
        method: Method,
        segments: &[&str],
        body: Option<&Value>,
    ) -> Result<(StatusCode, Value), ControlError> {
        let mut url = self.base.clone();
        url.path_segments_mut()
            .map_err(|()| ControlError::Network("the control URL cannot take a path".to_owned()))?
            .pop_if_empty()
            .extend(segments);
        let bytes = body.map(serde_json::to_vec).transpose().map_err(|error| {
            ControlError::Network(format!("the request does not serialize: {error}"))
        })?;
        let id = format!("msg_{}", uuid::Uuid::now_v7().simple());
        let timestamp = jiff::Timestamp::now().as_second();
        let signature = crypto::sign_webhook(
            &self.secret,
            &id,
            timestamp,
            &norbelys_mail::webhooks::control_payload(
                method.as_str(),
                url[url::Position::BeforePath..].as_ref(),
                bytes.as_deref().unwrap_or_default(),
            ),
        );
        let mut request = self
            .client
            .request(method, url)
            .header("webhook-id", id)
            .header("norbelys-control-version", "2")
            .header("webhook-timestamp", timestamp.to_string())
            .header("webhook-signature", signature);
        if let Some(bytes) = bytes {
            request = request
                .header(reqwest::header::CONTENT_TYPE, "application/json")
                .body(bytes);
        }
        let response = request
            .send()
            .await
            .map_err(|error| ControlError::Network(error.to_string()))?;
        let status = response.status();
        let body = response
            .bytes()
            .await
            .map_err(|error| ControlError::Network(error.to_string()))?;
        if body.len() > ANSWER_LIMIT {
            return Err(ControlError::Answer {
                status: status.as_u16(),
                detail: "the answer is larger than expected".to_owned(),
            });
        }
        let json = if body.is_empty() {
            Value::Null
        } else {
            serde_json::from_slice(&body).map_err(|_| ControlError::Answer {
                status: status.as_u16(),
                detail: "the answer is not JSON".to_owned(),
            })?
        };
        Ok((status, json))
    }
}

/// The `detail` of a problem answer, else its status.
fn detail(status: StatusCode, body: &Value) -> String {
    body.get("detail")
        .and_then(Value::as_str)
        .map_or_else(|| format!("status {status}"), str::to_owned)
}

/// A TXT record rendered by the managed MTA for the customer to publish. The value and the
/// publication advice come from the MTA, which owns its sending address and DNS configuration.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MtaDnsRecord {
    /// The DNS owner name.
    pub name: String,
    /// The TXT value.
    pub value: String,
    /// How to publish the value alongside existing DNS records.
    pub note: String,
}

/// Publication instructions; preparing them does not prove domain ownership.
pub struct MtaDomainDns {
    /// SPF instruction to merge into the existing sender policy.
    pub spf: Option<MtaDnsRecord>,
    /// Default DMARC instruction; preserve an existing policy.
    pub dmarc: Option<MtaDnsRecord>,
    /// Public DKIM TXT owner and value when key preparation has finished.
    pub dkim: Option<(String, String)>,
}

/// What the managed MTA knows of a sending domain registered there.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MtaDomain {
    /// The MTA proved the domain's ownership itself.
    Verified {
        /// The SPF record authorizing the managed MTA, with advice for an existing SPF record.
        spf: Option<MtaDnsRecord>,
        /// The minimum DMARC policy, with advice to preserve an existing policy.
        dmarc: Option<MtaDnsRecord>,
        /// The TXT record of the domain's DKIM key to publish, as its name and value, once the
        /// key exists: the MTA's provisioning helper creates it moments after the first
        /// verification, so the first answer may not carry it yet.
        dkim: Option<(String, String)>,
    },
    /// The MTA has not proven ownership yet: its own DNS lookup has not seen the record (another
    /// resolver's cache), or failed. Its words; the next check asks again.
    Unverified(String),
}

/// What the managed MTA says of a login, for the daily check of a `norbelys` connection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LoginState {
    /// It exists, enabled, and posts its evidence to a route.
    Active,
    /// It exists but was disabled.
    Disabled,
    /// The MTA does not know it.
    Missing,
    /// It reports to no route, so its evidence goes nowhere.
    Unrouted,
}

impl Control {
    /// Prepare a domain's DNS instructions without granting a login or assuming ownership.
    ///
    /// # Errors
    /// The authenticated control service cannot render the domain.
    pub async fn prepare_domain(
        &self,
        name: &str,
        ownership: &str,
    ) -> Result<MtaDomainDns, ControlError> {
        let (status, body) = self
            .call(
                Method::POST,
                &["v1", "domains"],
                Some(&json!({ "name":name, "ownership_token":ownership })),
            )
            .await?;
        if !matches!(status, StatusCode::OK | StatusCode::CREATED) {
            return Err(ControlError::Answer {
                status: status.as_u16(),
                detail: detail(status, &body),
            });
        }
        Ok(MtaDomainDns {
            spf: txt_record(&body, name),
            dmarc: txt_record(&body, &format!("_dmarc.{name}")),
            dkim: dkim_record(&body, name),
        })
    }
    /// Registers the sending domain `name` on the MTA with `ownership`, the whole value of the
    /// `_norbelys.<name>` TXT record its owner publishes for Norbelys, so the one record proves
    /// the domain to both; asks the MTA to verify it while it is not; and reads the SPF, DMARC
    /// and DKIM records the MTA renders for it. Every step repeats safely: registering again answers the
    /// registered domain, and verifying a verified one changes nothing.
    ///
    /// # Errors
    ///
    /// No answer, or an answer outside the contract (the domain refused as a name, a server
    /// error).
    pub async fn register_domain(
        &self,
        name: &str,
        ownership: &str,
    ) -> Result<MtaDomain, ControlError> {
        let (status, body) = self
            .call(
                Method::POST,
                &["v1", "domains"],
                Some(&json!({ "name": name, "ownership_token": ownership })),
            )
            .await?;
        if !matches!(status, StatusCode::OK | StatusCode::CREATED) {
            return Err(ControlError::Answer {
                status: status.as_u16(),
                detail: detail(status, &body),
            });
        }
        let body = if body.get("verified_at").is_some_and(|at| !at.is_null()) {
            body
        } else {
            match self
                .call(Method::POST, &["v1", "domains", name, "verify"], None)
                .await?
            {
                (StatusCode::OK, body) => body,
                (status @ (StatusCode::CONFLICT | StatusCode::SERVICE_UNAVAILABLE), body) => {
                    return Ok(MtaDomain::Unverified(detail(status, &body)));
                }
                (status, body) => {
                    return Err(ControlError::Answer {
                        status: status.as_u16(),
                        detail: detail(status, &body),
                    });
                }
            }
        };
        Ok(MtaDomain::Verified {
            spf: txt_record(&body, name),
            dmarc: txt_record(&body, &format!("_dmarc.{name}")),
            dkim: dkim_record(&body, name),
        })
    }

    /// The state of the login `username` on the MTA.
    ///
    /// # Errors
    ///
    /// No answer, or an answer outside the contract.
    pub async fn login(&self, username: &str) -> Result<LoginState, ControlError> {
        match self
            .call(Method::GET, &["v1", "accounts", username], None)
            .await?
        {
            (StatusCode::NOT_FOUND, _) => Ok(LoginState::Missing),
            (StatusCode::OK, body) if body.get("disabled_at").is_some_and(|at| !at.is_null()) => {
                Ok(LoginState::Disabled)
            }
            (StatusCode::OK, body) if body.get("route").is_none_or(Value::is_null) => {
                Ok(LoginState::Unrouted)
            }
            (StatusCode::OK, _) => Ok(LoginState::Active),
            (status, body) => Err(ControlError::Answer {
                status: status.as_u16(),
                detail: detail(status, &body),
            }),
        }
    }
}

/// The DKIM record among the `records` the MTA rendered for the domain `name`: the TXT record at
/// `<dkim_selector>._domainkey.<name>`, as its name and value; absent until the key exists.
fn dkim_record(body: &Value, name: &str) -> Option<(String, String)> {
    let selector = body.get("dkim_selector").and_then(Value::as_str)?;
    let owner = format!("{selector}._domainkey.{name}");
    txt_record(body, &owner).map(|record| (record.name, record.value))
}

/// Reads only the TXT record at the requested owner name, preserving the MTA's publication
/// advice. MX and ownership records are not instructions to change the customer's sending DNS.
fn txt_record(body: &Value, owner: &str) -> Option<MtaDnsRecord> {
    body.get("records")?.as_array()?.iter().find_map(|record| {
        let matches = record.get("type").and_then(Value::as_str) == Some("TXT")
            && record.get("name").and_then(Value::as_str) == Some(owner);
        let content = record.get("content").and_then(Value::as_str)?;
        matches.then(|| MtaDnsRecord {
            name: owner.to_owned(),
            value: content.to_owned(),
            note: record
                .get("note")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_owned(),
        })
    })
}

/// `provider.norbelys.provision`: provisions one `norbelys` connection (see the module).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NorbelysProvision {
    /// The connection to provision.
    pub connection: Id<Connection>,
}

/// What the job learns from the control API.
enum Provisioned {
    /// The login's password, answered once.
    Login(SecretString),
    /// The MTA refused what a person must fix.
    Refused(String),
}

impl Job for NorbelysProvision {
    const KIND: &'static str = "provider.norbelys.provision";
    const QUEUE: Queue = Queue::Maintenance;
    const EFFECT: Effect = Effect::ExternalRetryable;

    fn unique_key(&self) -> Option<String> {
        Some(self.connection.to_string())
    }

    async fn run(self, cx: &mut JobContext) -> Result<Outcome, JobError> {
        if cx.progress().is_some() {
            return Ok(Outcome::Done);
        }
        let workspace = cx.workspace();
        let keys = cx.env::<Keys>()?.clone();
        let env = cx.env::<Env>()?.clone();
        let mut tx = cx.db().begin_in(workspace).await?;
        let row = sqlx::query!(
            r#"SELECT c.status, c.credential_version, c.paused, c.account_email,
                      w.id AS "webhook?: Id<ProviderWebhook>", w.signing_secret
                 FROM connections c
                 LEFT JOIN provider_webhooks w ON w.workspace_id = c.workspace_id AND w.connection_id = c.id
                WHERE c.workspace_id = $1 AND c.id = $2 AND c.provider = 'norbelys'"#,
            workspace.uuid(),
            self.connection.uuid(),
        )
        .fetch_optional(&mut *tx)
        .await?;
        let receives: bool = sqlx::query_scalar(
            "SELECT imap IS NOT NULL FROM connections WHERE workspace_id = $1 AND id = $2",
        )
        .bind(workspace.uuid())
        .bind(self.connection.uuid())
        .fetch_optional(&mut *tx)
        .await?
        .unwrap_or(false);
        tx.commit().await?;
        let Some(row) = row else {
            return Ok(Outcome::Done);
        };
        if row.status != Status::Verifying.as_str() {
            return Ok(Outcome::Done);
        }
        let outcome = match (&env.control, row.webhook, &row.signing_secret) {
            (None, _, _) => Provisioned::Refused(
                "The managed MTA is not configured on this deployment.".to_owned(),
            ),
            (Some(control), Some(webhook), Some(sealed)) => {
                let secret = credentials::open_webhook_key(&keys, workspace, webhook, sealed)
                    .map_err(|error| JobError::Failed(error.to_string()))?;
                let url = env.settings.webhook_url(webhook);
                let sends = if row.account_email.contains('@') {
                    true
                } else {
                    let mut tx = cx.db().begin_in(workspace).await?;
                    let purpose =
                        super::domains::mail_access(&mut tx, workspace, &row.account_email)
                            .await
                            .map_err(|error| JobError::Failed(error.to_string()))?;
                    tx.commit().await?;
                    purpose.sends()
                };
                provision(
                    control,
                    &super::managed::username(workspace, &row.account_email),
                    webhook,
                    &url,
                    &secret,
                    receives,
                    sends,
                )
                .await
                .map_err(|error| JobError::Failed(error.to_string()))?
            }
            (Some(_), _, _) => {
                return Err(JobError::Failed(
                    "the connection has no provider webhook secret".to_owned(),
                ));
            }
        };

        let mut chunk = cx.begin().await?;
        let current = sqlx::query!(
            "SELECT status, credential_version FROM connections WHERE workspace_id = $1 AND id = $2 FOR UPDATE",
            workspace.uuid(),
            self.connection.uuid(),
        )
        .fetch_optional(&mut **chunk.tx())
        .await?;
        if !current.is_some_and(|current| {
            current.status == row.status && current.credential_version == row.credential_version
        }) {
            return Ok(Outcome::Yield {
                after: Duration::ZERO,
            });
        }
        let (event, detail) = match outcome {
            Provisioned::Login(password) => {
                let sealed = credentials::seal(
                    &keys,
                    workspace,
                    self.connection,
                    &Credential::Password(password),
                )
                .map_err(|error| JobError::Failed(error.to_string()))?;
                sqlx::query_scalar!(
                    "SELECT set_connection_credential($1, $2, $3)",
                    workspace.uuid(),
                    self.connection.uuid(),
                    sealed,
                )
                .fetch_one(&mut **chunk.tx())
                .await?;
                jobs::enqueue(
                    chunk.tx(),
                    workspace,
                    &ConnectionCheck {
                        connection: self.connection,
                    },
                    Some(Timestamp(jiff::Timestamp::now()).plus(Duration::from_secs(60))),
                )
                .await?;
                (None, None)
            }
            Provisioned::Refused(detail) => (Some(HealthEvent::ProvisionFailed), Some(detail)),
        };
        sqlx::query!(
            "UPDATE connections SET checked_at = now() WHERE workspace_id = $1 AND id = $2",
            workspace.uuid(),
            self.connection.uuid(),
        )
        .execute(&mut **chunk.tx())
        .await?;
        if let Some(event) = event {
            health::apply(
                chunk.tx(),
                workspace,
                self.connection,
                Status::Verifying,
                row.paused,
                event,
                detail.as_deref(),
            )
            .await?;
        }
        cx.checkpoint(chunk, json!({ "provisioned": detail.is_none() }))
            .await?;
        Ok(Outcome::Done)
    }
}

/// Internal domain relay names are bound to the workspace's full UUID.
fn domain_login(username: &str) -> bool {
    username
        .split_once('@')
        .and_then(|(local, _)| local.strip_prefix("norbelys-"))
        .is_some_and(|id| id.len() == 32 && uuid::Uuid::parse_str(id).is_ok())
}

/// The login and the route of `username` at the MTA.
async fn provision(
    control: &Control,
    username: &str,
    webhook: Id<ProviderWebhook>,
    url: &str,
    secret: &SecretString,
    receives: bool,
    sends: bool,
) -> Result<Provisioned, ControlError> {
    let (status, body) = control
        .call(Method::GET, &["v1", "accounts", username], None)
        .await?;
    let issued = match status {
        StatusCode::OK => {
            control
                .call(
                    Method::POST,
                    &["v1", "accounts", username, "password"],
                    None,
                )
                .await?
        }
        StatusCode::NOT_FOUND => control
            .call(
                Method::POST,
                &["v1", "accounts"],
                Some(&json!({ "username": username, "kind": if domain_login(username) { "service" } else { "mailbox" }, "rate_class": "customer" })),
            )
            .await?,
        other => {
            return Err(ControlError::Answer {
                status: other.as_u16(),
                detail: detail(other, &body),
            });
        }
    };
    let password = match issued {
        (StatusCode::OK | StatusCode::CREATED, body) => {
            match body.get("password").and_then(Value::as_str) {
                Some(password) => SecretString::from(password.to_owned()),
                None => {
                    return Err(ControlError::Answer {
                        status: 200,
                        detail: "the answer carries no password".to_owned(),
                    });
                }
            }
        }
        (status @ (StatusCode::CONFLICT | StatusCode::UNPROCESSABLE_ENTITY), body) => {
            return Ok(Provisioned::Refused(format!(
                "The managed MTA refused the login: {}",
                detail(status, &body)
            )));
        }
        (status, body) => {
            return Err(ControlError::Answer {
                status: status.as_u16(),
                detail: detail(status, &body),
            });
        }
    };
    if domain_login(username) {
        let (status, body) = control
            .call(
                Method::PATCH,
                &["v1", "accounts", username],
                Some(&json!({"grant": sends, "catch_all": receives})),
            )
            .await?;
        if !status.is_success() {
            return Err(ControlError::Answer {
                status: status.as_u16(),
                detail: detail(status, &body),
            });
        }
    }
    let route = json!({ "url": url, "secret": secret.expose_secret(), "usernames": [username] });
    let webhook = webhook.to_string();
    match control
        .call(Method::PUT, &["v1", "routes", &webhook], Some(&route))
        .await?
    {
        (status, _) if status.is_success() => Ok(Provisioned::Login(password)),
        (status @ (StatusCode::CONFLICT | StatusCode::UNPROCESSABLE_ENTITY), body) => {
            Ok(Provisioned::Refused(format!(
                "The managed MTA refused the evidence route: {}",
                detail(status, &body)
            )))
        }
        (status, body) => Err(ControlError::Answer {
            status: status.as_u16(),
            detail: detail(status, &body),
        }),
    }
}

#[cfg(test)]
mod tests {
    use std::sync::{Arc, Mutex};

    use base64::Engine as _;
    use tokio::net::TcpListener;

    use super::*;

    /// What a fake control API received, in order: method, path and JSON body.
    type Seen = Arc<Mutex<Vec<(String, String, Value)>>>;

    /// A fake control API on loopback that answers each request by `answer(method, path)`;
    /// returns the client of it and what it received.
    async fn fake(answer: fn(&str, &str) -> (u16, Value)) -> (Control, Seen) {
        let seen: Seen = Arc::default();
        let recorder = Arc::clone(&seen);
        let app = axum::Router::new().fallback(move |request: axum::extract::Request| {
            let recorder = Arc::clone(&recorder);
            async move {
                let (parts, body) = request.into_parts();
                let body = axum::body::to_bytes(body, 65_536).await.unwrap_or_default();
                let json: Value = serde_json::from_slice(&body).unwrap_or(Value::Null);
                let (method, path) = (parts.method.to_string(), parts.uri.path().to_owned());
                let (status, reply) = answer(&method, &path);
                recorder.lock().unwrap().push((method, path, json));
                (StatusCode::from_u16(status).unwrap(), axum::Json(reply))
            }
        });
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let origin = format!("http://{}", listener.local_addr().unwrap());
        tokio::spawn(async move { axum::serve(listener, app).await });
        let secret = SecretString::from(format!(
            "whsec_{}",
            base64::engine::general_purpose::STANDARD.encode([7_u8; 32])
        ));
        (
            Control::new(Url::parse(&origin).unwrap(), &secret, false).unwrap(),
            seen,
        )
    }

    /// `acme.example` as the MTA renders it: verified or not, with its DKIM record once `key`.
    fn rendered(verified: bool, key: bool) -> Value {
        let mut records = vec![
            json!({
                "type": "TXT", "name": "_norbelys.acme.example",
                "content": "norbelys-verification=t", "note": "",
            }),
            json!({
                "type": "TXT", "name": "acme.example",
                "content": "v=spf1 ip4:192.0.2.10 ~all", "note": "Merge into existing SPF",
            }),
            json!({
                "type": "TXT", "name": "_dmarc.acme.example",
                "content": "v=DMARC1; p=none", "note": "Keep an existing DMARC policy",
            }),
            json!({
                "type": "MX", "name": "acme.example", "content": "mail.acme.example",
            }),
        ];
        if key {
            records.push(json!({
                "type": "TXT", "name": "norbelys._domainkey.acme.example",
                "content": "v=DKIM1; k=rsa; p=MIIB", "note": "",
            }));
        }
        json!({
            "name": "acme.example",
            "ownership_token": "norbelys-verification=t",
            "verified_at": verified.then_some("2026-10-02T00:00:00Z"),
            "dkim_selector": "norbelys",
            "dkim_public": key.then_some("MIIB"),
            "created_at": "2026-10-01T00:00:00Z",
            "records": records,
        })
    }

    /// The calls a fake received: method and path.
    fn calls(seen: &Seen) -> Vec<(String, String)> {
        seen.lock()
            .unwrap()
            .iter()
            .map(|(method, path, _)| (method.clone(), path.clone()))
            .collect()
    }

    /// A sending domain is registered with the very value its owner publishes for Norbelys,
    /// verified, and its SPF, DMARC and DKIM records read from what the MTA renders, preserving
    /// publication advice and excluding other records; a domain the MTA verified
    /// before is not verified again, and its key may still be pending; the MTA not seeing the
    /// record yet is an answer to wait on, while a refusal outside the contract is an error.
    #[tokio::test]
    async fn registers_and_verifies_a_domain() {
        fn fresh(_: &str, path: &str) -> (u16, Value) {
            match path {
                "/v1/domains" => (201, rendered(false, false)),
                _ => (200, rendered(true, true)),
            }
        }
        let (control, seen) = fake(fresh).await;
        assert_eq!(
            control
                .register_domain("acme.example", "norbelys-verification=t")
                .await
                .unwrap(),
            MtaDomain::Verified {
                spf: Some(MtaDnsRecord {
                    name: "acme.example".to_owned(),
                    value: "v=spf1 ip4:192.0.2.10 ~all".to_owned(),
                    note: "Merge into existing SPF".to_owned(),
                }),
                dmarc: Some(MtaDnsRecord {
                    name: "_dmarc.acme.example".to_owned(),
                    value: "v=DMARC1; p=none".to_owned(),
                    note: "Keep an existing DMARC policy".to_owned(),
                }),
                dkim: Some((
                    "norbelys._domainkey.acme.example".to_owned(),
                    "v=DKIM1; k=rsa; p=MIIB".to_owned()
                ))
            }
        );
        assert_eq!(
            calls(&seen),
            [
                ("POST".to_owned(), "/v1/domains".to_owned()),
                (
                    "POST".to_owned(),
                    "/v1/domains/acme.example/verify".to_owned()
                ),
            ]
        );
        assert_eq!(
            seen.lock().unwrap()[0].2,
            json!({ "name": "acme.example", "ownership_token": "norbelys-verification=t" })
        );

        fn known(_: &str, _: &str) -> (u16, Value) {
            (200, rendered(true, false))
        }
        let (control, seen) = fake(known).await;
        assert!(matches!(
            control
                .register_domain("acme.example", "norbelys-verification=t")
                .await
                .unwrap(),
            MtaDomain::Verified {
                spf: Some(_),
                dmarc: Some(_),
                dkim: None
            }
        ));
        assert_eq!(
            calls(&seen).len(),
            1,
            "a verified domain is not verified again"
        );

        fn unseen(_: &str, path: &str) -> (u16, Value) {
            match path {
                "/v1/domains" => (201, rendered(false, false)),
                _ => (
                    409,
                    json!({ "code": "conflict", "detail": "the TXT record does not hold the ownership token yet" }),
                ),
            }
        }
        let (control, _) = fake(unseen).await;
        assert_eq!(
            control
                .register_domain("acme.example", "norbelys-verification=t")
                .await
                .unwrap(),
            MtaDomain::Unverified(
                "the TXT record does not hold the ownership token yet".to_owned()
            )
        );

        fn refused(_: &str, _: &str) -> (u16, Value) {
            (
                422,
                json!({ "code": "validation_failed", "detail": "name must be a lowercase fully qualified domain name" }),
            )
        }
        let (control, _) = fake(refused).await;
        assert!(matches!(
            control
                .register_domain("acme.example", "norbelys-verification=t")
                .await,
            Err(ControlError::Answer { status: 422, .. })
        ));
    }

    /// The daily check of a `norbelys` connection reads its login on the MTA: enabled with a
    /// route, disabled, without a route, unknown, or an answer outside the contract.
    #[tokio::test]
    async fn reads_a_logins_state() {
        fn accounts(_: &str, path: &str) -> (u16, Value) {
            match path {
                "/v1/accounts/live@acme.example" => (
                    200,
                    json!({ "username": "live@acme.example", "route": "pwh_1", "disabled_at": null }),
                ),
                "/v1/accounts/off@acme.example" => (
                    200,
                    json!({ "username": "off@acme.example", "route": "pwh_1", "disabled_at": "2026-10-01T00:00:00Z" }),
                ),
                "/v1/accounts/mute@acme.example" => (
                    200,
                    json!({ "username": "mute@acme.example", "route": null, "disabled_at": null }),
                ),
                "/v1/accounts/boom@acme.example" => (500, json!({ "detail": "internal" })),
                _ => (404, json!({ "code": "not_found", "detail": "no account" })),
            }
        }
        let (control, _) = fake(accounts).await;
        for (username, expected) in [
            ("live@acme.example", LoginState::Active),
            ("off@acme.example", LoginState::Disabled),
            ("mute@acme.example", LoginState::Unrouted),
            ("gone@acme.example", LoginState::Missing),
        ] {
            assert_eq!(
                control.login(username).await.unwrap(),
                expected,
                "{username}"
            );
        }
        assert!(matches!(
            control.login("boom@acme.example").await,
            Err(ControlError::Answer { status: 500, .. })
        ));
    }
}
