import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  // Generated by SQLx, Wrangler, the SDK generator, the TanStack Router plugin and the shadcn
  // CLI; keep each tool's canonical output.
  ignorePatterns: [
    // Code-generation tools are authored source; only their output is generated.
    ...(ultracite.ignorePatterns ?? []).filter(
      (pattern) => pattern !== "**/codegen"
    ),
    ".sqlx/**",
    "crates/server/openapi.json",
    "apps/docs/openapi.json",
    // Released prompts retain their original text.
    "crates/ai/prompts/**",
    "apps/app/worker/env.d.ts",
    "apps/app/src/routeTree.gen.ts",
    "apps/app/src/components/ui/**",
    "sdks/typescript/src/generated/**",
    // Written by `bun brand/build.ts` from the brand's sources.
    "brand/rasterize.html",
  ],
});
