import { defineConfig } from "oxlint";
import astro from "ultracite/oxlint/astro";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";

export default defineConfig({
  extends: [core, react, astro, tanstack],
  ignorePatterns: [
    // Check the generator implementation as well as application code.
    ...(core.ignorePatterns ?? []).filter(
      (pattern) => pattern !== "**/codegen"
    ),
    "apps/app/worker/env.d.ts",
    // Generated by the TanStack Router plugin and the shadcn CLI (`shadcn add` rewrites them).
    "apps/app/src/routeTree.gen.ts",
    "apps/app/src/components/ui/**",
    "sdks/typescript/src/generated/**",
    // Third-party agent skills, kept exactly as their installer wrote them.
    ".github/skills/**",
    ".claude/skills/**",
  ],
});
