//! Verifies Standard Webhooks batches from the managed MTA crate `norbelys-smtp`.
//!
//! - **Headers**, per Standard Webhooks
//!   (<https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md>):
//!   `webhook-id`, `webhook-timestamp` (Unix seconds) and `webhook-signature` (space-separated
//!   `v1,<base64>` entries); each `v1` signature is the base64 HMAC-SHA256 of
//!   `{webhook-id}.{webhook-timestamp}.{body}` under the provider webhook's secret (24 to 64
//!   random bytes, generated by Norbelys when it registers the route at the MTA). Any listed
//!   `v1` signature that verifies is enough, which lets a secret rotate. The MTA signs every
//!   attempt anew with a fresh `webhook-id` and timestamp, so the timestamp must be within
//!   [`MAX_AGE`] (the specification's default tolerance) of now; deduplication is by each
//!   event's `event_id`, never by `webhook-id`.
//! - **Body**: one batch of 1 to [`MAX_BATCH`] events of the route (tighter than the crate-wide
//!   [`super::MAX_EVENTS`] cap), as JSON:
//!
//!   ```json
//!   {"type": "mta.events", "timestamp": "2026-10-01T12:00:00Z", "data": {"events": [
//!     {"event_id": "3f6c…", "internet_message_id": "<m1.t1.tag@mail.example.com>",
//!      "username": "relay@example.com", "recipient": "alice@example.net",
//!      "queue_id": "4ZQ1aB2cDe", "kind": "delivered", "enhanced_status": "2.0.0",
//!      "detail": "250 2.0.0 OK", "provenance": "smtp_reply",
//!      "observed_at": "2026-10-01T11:59:58.123456Z"}]}}
//!   ```
//!
//!   `type` is always `mta.events`; `timestamp` is when the MTA made the request (freshness is
//!   judged by the signed header). Each event: `event_id` (1 to 256 visible ASCII characters,
//!   unique per route and stable across retries: the replay key), `kind` (`delivered`: the next
//!   hop accepted the message, never a claim about the inbox; `deferred`; `bounced`; `accepted`
//!   and `complaint`), `provenance` (`smtp_reply`: the next hop's SMTP reply, read by the MTA
//!   itself; `verp_dsn`: a delivery status notification returned to the message's VERP return
//!   path, which proves the message was the caller's but not who wrote the report;
//!   `fbl_arf_dkim` and `feedback_id_only` for abuse reports) and `observed_at` (RFC 3339) are
//!   required; `internet_message_id` (as the MTA saw it, angle brackets included), `username`
//!   (the MTA login that submitted the message), `recipient`, `queue_id` (Postfix's),
//!   `enhanced_status` (RFC 3463) and `detail` (at most 2,000 characters) are present when
//!   known.
//!
//! The MTA login (`username`) never chooses a tenant: the webhook's URL already names the
//! connection. The caller's message id travels inside the `internet_message_id` this library
//! composed, which the caller decodes; the queue id becomes [`Event::provider_message_id`].

use aws_lc_rs::hmac;
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use jiff::{SignedDuration, Timestamp};
use serde::Deserialize;
use serde_json::value::RawValue;

use super::{Event, EventKind, KeyError, ParseError, Provenance, Receipt, VerifyError};
use crate::status::EnhancedStatus;

/// How far from now a signed timestamp may be.
pub const MAX_AGE: SignedDuration = SignedDuration::from_mins(5);
/// The most events one batch carries.
pub const MAX_BATCH: usize = 100;

/// A provider webhook's Standard Webhooks secret.
#[derive(Debug, Clone)]
pub struct NorbelysKey(hmac::Key);

impl NorbelysKey {
    /// The key from the secret's raw bytes (not its `whsec_` text form).
    ///
    /// # Errors
    ///
    /// The secret is shorter than 24 or longer than 64 bytes.
    pub fn new(secret: &[u8]) -> Result<Self, KeyError> {
        if !(24..=64).contains(&secret.len()) {
            return Err(KeyError("a Standard Webhooks secret has 24 to 64 bytes"));
        }
        Ok(Self(hmac::Key::new(hmac::HMAC_SHA256, secret)))
    }
}

/// Verifies one batch from the managed MTA and returns one receipt per event.
///
/// # Errors
///
/// [`VerifyError`]: too large (the body, or more than [`MAX_BATCH`] events), missing headers, no
/// verifying `v1` signature, a stale timestamp, a body that is not an `mta.events` batch of at
/// least one event, or an event without `event_id`.
pub fn verify(
    key: &NorbelysKey,
    headers: &http::HeaderMap,
    body: &[u8],
    now: Timestamp,
) -> Result<Vec<Receipt>, VerifyError> {
    if body.len() > super::MAX_BODY {
        return Err(VerifyError::TooLarge);
    }
    let missing = || VerifyError::Unauthorized("a Standard Webhooks header is missing");
    let id = super::header(headers, "webhook-id")
        .filter(|id| !id.is_empty() && id.len() <= 256)
        .ok_or_else(missing)?;
    let timestamp = super::header(headers, "webhook-timestamp")
        .filter(|stamp| stamp.len() <= 20)
        .ok_or_else(missing)?;
    let signatures = super::header(headers, "webhook-signature")
        .filter(|list| list.len() <= 4096)
        .ok_or_else(missing)?;
    if !signature_matches(key, id, timestamp, body, signatures) {
        return Err(VerifyError::Unauthorized("no v1 signature verifies"));
    }
    let seconds = timestamp
        .parse()
        .map_err(|_| VerifyError::Unauthorized("the timestamp is not a number"))?;
    super::fresh(seconds, now, MAX_AGE)?;

    #[derive(Deserialize)]
    struct Batch<'a> {
        #[serde(rename = "type")]
        kind: &'a str,
        #[serde(borrow)]
        data: Data<'a>,
    }
    #[derive(Deserialize)]
    struct Data<'a> {
        #[serde(borrow)]
        events: Vec<&'a RawValue>,
    }
    let batch: Batch<'_> = serde_json::from_slice(body)
        .map_err(|error| VerifyError::InvalidPayload(error.to_string()))?;
    if batch.kind != "mta.events" {
        return Err(VerifyError::InvalidPayload(format!(
            "unknown batch type `{}`",
            crate::text::bounded(batch.kind, 40)
        )));
    }
    if batch.data.events.len() > MAX_BATCH {
        return Err(VerifyError::TooLarge);
    }
    if batch.data.events.is_empty() {
        return Err(VerifyError::InvalidPayload("an empty batch".to_owned()));
    }
    batch
        .data
        .events
        .into_iter()
        .map(|raw| {
            #[derive(Deserialize)]
            struct Id {
                event_id: Option<String>,
            }
            let parsed: Id = serde_json::from_str(raw.get())
                .map_err(|error| VerifyError::InvalidPayload(error.to_string()))?;
            let event_id = super::event_id(parsed.event_id.as_deref())?;
            Ok(Receipt {
                event_id,
                raw: raw.get().as_bytes().to_vec(),
            })
        })
        .collect()
}

/// Whether any `v1` entry of a `webhook-signature` header is the HMAC-SHA256, under `key`, of
/// `{id}.{timestamp}.{body}`. Entries of other versions are ignored; the comparison is constant
/// time.
fn signature_matches(
    key: &NorbelysKey,
    id: &str,
    timestamp: &str,
    body: &[u8],
    header: &str,
) -> bool {
    let mut signed = Vec::with_capacity(id.len() + timestamp.len() + body.len() + 2);
    signed.extend_from_slice(id.as_bytes());
    signed.push(b'.');
    signed.extend_from_slice(timestamp.as_bytes());
    signed.push(b'.');
    signed.extend_from_slice(body);
    header
        .split_whitespace()
        .filter_map(|entry| entry.strip_prefix("v1,"))
        .filter_map(|encoded| STANDARD.decode(encoded).ok())
        .any(|signature| hmac::verify(&key.0, &signed, &signature).is_ok())
}

/// The one event of a stored receipt.
///
/// # Errors
///
/// The receipt breaks the MTA's event contract: an unknown kind, a missing or unknown
/// provenance, no `observed_at`, a malformed enhanced status.
pub fn events(raw: &[u8]) -> Result<Vec<Event>, ParseError> {
    #[derive(Deserialize)]
    struct Wire {
        event_id: String,
        internet_message_id: Option<String>,
        recipient: Option<String>,
        queue_id: Option<String>,
        kind: String,
        enhanced_status: Option<String>,
        detail: Option<String>,
        provenance: String,
        observed_at: String,
    }
    let wire: Wire = serde_json::from_slice(raw).map_err(|error| ParseError(error.to_string()))?;
    let kind = match wire.kind.as_str() {
        "accepted" => EventKind::Accepted,
        "deferred" => EventKind::Deferred,
        "delivered" => EventKind::Delivered,
        "bounced" => EventKind::Bounced,
        "complaint" => EventKind::Complaint,
        other => {
            return Err(ParseError(format!(
                "unknown kind `{}`",
                crate::text::bounded(other, 40)
            )));
        }
    };
    let provenance = match wire.provenance.as_str() {
        "smtp_reply" => Provenance::SmtpReply,
        "verp_dsn" => Provenance::VerpDsn,
        "fbl_arf_dkim" => Provenance::FblArfDkim,
        "feedback_id_only" => Provenance::FeedbackIdOnly,
        other => {
            return Err(ParseError(format!(
                "unknown provenance `{}`",
                crate::text::bounded(other, 40)
            )));
        }
    };
    let status = match wire
        .enhanced_status
        .as_deref()
        .map(str::trim)
        .filter(|status| !status.is_empty())
    {
        None => None,
        Some(status) => Some(
            status
                .parse::<EnhancedStatus>()
                .map_err(|error| ParseError(error.to_string()))?,
        ),
    };
    let observed_at: Timestamp = wire
        .observed_at
        .parse()
        .map_err(|error: jiff::Error| ParseError(error.to_string()))?;
    let event_id =
        super::event_id(Some(&wire.event_id)).map_err(|error| ParseError(error.to_string()))?;
    let detail = wire.detail.as_deref();
    Ok(vec![Event {
        event_id,
        kind,
        message_id: None,
        internet_message_id: wire
            .internet_message_id
            .map(|id| crate::text::bounded(&id, 998)),
        provider_message_id: wire.queue_id.map(|id| crate::text::bounded(&id, 256)),
        recipient: super::recipient(wire.recipient.as_deref()),
        status,
        smtp_code: detail.and_then(super::smtp_code),
        diagnostic: super::diagnostic(detail),
        observed_at,
        provenance: Some(provenance),
    }])
}

#[cfg(test)]
mod tests;
