/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/_account'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as NewRouteImport } from './routes/new'
import { Route as AccountIndexRouteImport } from './routes/_account/index'
import { Route as AccountAccountRouteImport } from './routes/_account/account'
import { Route as AccountWorkspacesRouteImport } from './routes/_account/workspaces'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as SignInIndexRouteImport } from './routes/sign-in.index'
import { Route as SignInLinkRouteImport } from './routes/sign-in.link'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as WSlugIndexRouteImport } from './routes/w.$slug/index'
import { Route as WSlugAnalyticsRouteImport } from './routes/w.$slug/analytics'
import { Route as WSlugApiKeysRouteImport } from './routes/w.$slug/api-keys'
import { Route as WSlugEventsRouteImport } from './routes/w.$slug/events'
import { Route as WSlugFieldsRouteImport } from './routes/w.$slug/fields'
import { Route as WSlugGroupsRouteImport } from './routes/w.$slug/groups'
import { Route as WSlugImportsRouteImport } from './routes/w.$slug/imports'
import { Route as WSlugLogsRouteImport } from './routes/w.$slug/logs'
import { Route as WSlugPreflightRouteImport } from './routes/w.$slug/preflight'
import { Route as WSlugQuotasRouteImport } from './routes/w.$slug/quotas'
import { Route as WSlugSettingsRouteImport } from './routes/w.$slug/settings'
import { Route as WSlugSuppressionsRouteImport } from './routes/w.$slug/suppressions'
import { Route as WSlugCampaignsIndexRouteImport } from './routes/w.$slug/campaigns.index'
import { Route as WSlugCampaignsCampaignIdRouteImport } from './routes/w.$slug/campaigns.$campaignId'
import { Route as WSlugDomainsIndexRouteImport } from './routes/w.$slug/domains.index'
import { Route as WSlugDomainsDomainIdRouteImport } from './routes/w.$slug/domains.$domainId'
import { Route as WSlugImportsIndexRouteImport } from './routes/w.$slug/imports.index'
import { Route as WSlugImportsExportsRouteImport } from './routes/w.$slug/imports.exports'
import { Route as WSlugImportsImportIdRouteImport } from './routes/w.$slug/imports_.$importId'
import { Route as WSlugImportsNewRouteImport } from './routes/w.$slug/imports_.new'
import { Route as WSlugInboxIndexRouteImport } from './routes/w.$slug/inbox.index'
import { Route as WSlugInboxThreadIdRouteImport } from './routes/w.$slug/inbox.$threadId'
import { Route as WSlugMailboxesIndexRouteImport } from './routes/w.$slug/mailboxes.index'
import { Route as WSlugMailboxesConnectionIdRouteImport } from './routes/w.$slug/mailboxes.$connectionId'
import { Route as WSlugMailboxesNewRouteImport } from './routes/w.$slug/mailboxes.new'
import { Route as WSlugMessagesIndexRouteImport } from './routes/w.$slug/messages.index'
import { Route as WSlugMessagesMessageIdRouteImport } from './routes/w.$slug/messages.$messageId'
import { Route as WSlugMessagesNewRouteImport } from './routes/w.$slug/messages.new'
import { Route as WSlugPeopleIndexRouteImport } from './routes/w.$slug/people.index'
import { Route as WSlugPeoplePersonIdRouteImport } from './routes/w.$slug/people.$personId'
import { Route as WSlugSegmentsIndexRouteImport } from './routes/w.$slug/segments.index'
import { Route as WSlugSegmentsSegmentIdRouteImport } from './routes/w.$slug/segments.$segmentId'
import { Route as WSlugWebhooksIndexRouteImport } from './routes/w.$slug/webhooks.index'
import { Route as WSlugWebhooksEndpointIdRouteImport } from './routes/w.$slug/webhooks.$endpointId'
import { Route as WSlugCampaignsCampaignIdIndexRouteImport } from './routes/w.$slug/campaigns.$campaignId.index'
import { Route as WSlugCampaignsCampaignIdEnrollmentsRouteImport } from './routes/w.$slug/campaigns.$campaignId.enrollments'
import { Route as WSlugCampaignsCampaignIdMessagesRouteImport } from './routes/w.$slug/campaigns.$campaignId.messages'
import { Route as WSlugCampaignsCampaignIdSequenceRouteImport } from './routes/w.$slug/campaigns.$campaignId.sequence'
import { Route as WSlugCampaignsCampaignIdSettingsRouteImport } from './routes/w.$slug/campaigns.$campaignId.settings'
import { Route as WSlugInboxReceivedIndexRouteImport } from './routes/w.$slug/inbox.received.index'
import { Route as WSlugInboxReceivedInboundIdRouteImport } from './routes/w.$slug/inbox.received.$inboundId'
import { Route as WSlugMailboxesConnectionIdIndexRouteImport } from './routes/w.$slug/mailboxes.$connectionId.index'
import { Route as WSlugMailboxesConnectionIdSettingsRouteImport } from './routes/w.$slug/mailboxes.$connectionId.settings'
import { Route as WSlugWebhooksEndpointIdIndexRouteImport } from './routes/w.$slug/webhooks.$endpointId.index'
import { Route as WSlugWebhooksEndpointIdSettingsRouteImport } from './routes/w.$slug/webhooks.$endpointId.settings'

const AccountRoute = AccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAccountRoute = AccountAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWorkspacesRoute = AccountWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AccountRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInLinkRoute = SignInLinkRouteImport.update({
  id: '/sign-in/link',
  path: '/sign-in/link',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugAnalyticsRoute = WSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugApiKeysRoute = WSlugApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugEventsRoute = WSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugFieldsRoute = WSlugFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugGroupsRoute = WSlugGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugImportsRoute = WSlugImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugLogsRoute = WSlugLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugPreflightRoute = WSlugPreflightRouteImport.update({
  id: '/preflight',
  path: '/preflight',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugQuotasRoute = WSlugQuotasRouteImport.update({
  id: '/quotas',
  path: '/quotas',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsRoute = WSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSuppressionsRoute = WSlugSuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugCampaignsIndexRoute = WSlugCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugCampaignsCampaignIdRoute =
  WSlugCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => WSlugRoute,
  } as any)
const WSlugDomainsIndexRoute = WSlugDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugDomainsDomainIdRoute = WSlugDomainsDomainIdRouteImport.update({
  id: '/domains/$domainId',
  path: '/domains/$domainId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugImportsIndexRoute = WSlugImportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugImportsRoute,
} as any)
const WSlugImportsExportsRoute = WSlugImportsExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => WSlugImportsRoute,
} as any)
const WSlugImportsImportIdRoute = WSlugImportsImportIdRouteImport.update({
  id: '/imports_/$importId',
  path: '/imports/$importId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugImportsNewRoute = WSlugImportsNewRouteImport.update({
  id: '/imports_/new',
  path: '/imports/new',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugInboxIndexRoute = WSlugInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugInboxThreadIdRoute = WSlugInboxThreadIdRouteImport.update({
  id: '/inbox/$threadId',
  path: '/inbox/$threadId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMailboxesIndexRoute = WSlugMailboxesIndexRouteImport.update({
  id: '/mailboxes/',
  path: '/mailboxes/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMailboxesConnectionIdRoute =
  WSlugMailboxesConnectionIdRouteImport.update({
    id: '/mailboxes/$connectionId',
    path: '/mailboxes/$connectionId',
    getParentRoute: () => WSlugRoute,
  } as any)
const WSlugMailboxesNewRoute = WSlugMailboxesNewRouteImport.update({
  id: '/mailboxes/new',
  path: '/mailboxes/new',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMessagesIndexRoute = WSlugMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMessagesMessageIdRoute = WSlugMessagesMessageIdRouteImport.update({
  id: '/messages/$messageId',
  path: '/messages/$messageId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMessagesNewRoute = WSlugMessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugPeopleIndexRoute = WSlugPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugPeoplePersonIdRoute = WSlugPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSegmentsIndexRoute = WSlugSegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSegmentsSegmentIdRoute = WSlugSegmentsSegmentIdRouteImport.update({
  id: '/segments/$segmentId',
  path: '/segments/$segmentId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugWebhooksIndexRoute = WSlugWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugWebhooksEndpointIdRoute = WSlugWebhooksEndpointIdRouteImport.update({
  id: '/webhooks/$endpointId',
  path: '/webhooks/$endpointId',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugCampaignsCampaignIdIndexRoute =
  WSlugCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WSlugCampaignsCampaignIdRoute,
  } as any)
const WSlugCampaignsCampaignIdEnrollmentsRoute =
  WSlugCampaignsCampaignIdEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => WSlugCampaignsCampaignIdRoute,
  } as any)
const WSlugCampaignsCampaignIdMessagesRoute =
  WSlugCampaignsCampaignIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => WSlugCampaignsCampaignIdRoute,
  } as any)
const WSlugCampaignsCampaignIdSequenceRoute =
  WSlugCampaignsCampaignIdSequenceRouteImport.update({
    id: '/sequence',
    path: '/sequence',
    getParentRoute: () => WSlugCampaignsCampaignIdRoute,
  } as any)
const WSlugCampaignsCampaignIdSettingsRoute =
  WSlugCampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WSlugCampaignsCampaignIdRoute,
  } as any)
const WSlugInboxReceivedIndexRoute = WSlugInboxReceivedIndexRouteImport.update({
  id: '/inbox/received/',
  path: '/inbox/received/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugInboxReceivedInboundIdRoute =
  WSlugInboxReceivedInboundIdRouteImport.update({
    id: '/inbox/received/$inboundId',
    path: '/inbox/received/$inboundId',
    getParentRoute: () => WSlugRoute,
  } as any)
const WSlugMailboxesConnectionIdIndexRoute =
  WSlugMailboxesConnectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WSlugMailboxesConnectionIdRoute,
  } as any)
const WSlugMailboxesConnectionIdSettingsRoute =
  WSlugMailboxesConnectionIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WSlugMailboxesConnectionIdRoute,
  } as any)
const WSlugWebhooksEndpointIdIndexRoute =
  WSlugWebhooksEndpointIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WSlugWebhooksEndpointIdRoute,
  } as any)
const WSlugWebhooksEndpointIdSettingsRoute =
  WSlugWebhooksEndpointIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WSlugWebhooksEndpointIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AccountIndexRoute
  '/activate': typeof ActivateRoute
  '/new': typeof NewRoute
  '/account': typeof AccountAccountRoute
  '/workspaces': typeof AccountWorkspacesRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/sign-in/link': typeof SignInLinkRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/sign-in/': typeof SignInIndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/api-keys': typeof WSlugApiKeysRoute
  '/w/$slug/events': typeof WSlugEventsRoute
  '/w/$slug/fields': typeof WSlugFieldsRoute
  '/w/$slug/groups': typeof WSlugGroupsRoute
  '/w/$slug/imports': typeof WSlugImportsRouteWithChildren
  '/w/$slug/logs': typeof WSlugLogsRoute
  '/w/$slug/preflight': typeof WSlugPreflightRoute
  '/w/$slug/quotas': typeof WSlugQuotasRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/suppressions': typeof WSlugSuppressionsRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/campaigns/$campaignId': typeof WSlugCampaignsCampaignIdRouteWithChildren
  '/w/$slug/domains/$domainId': typeof WSlugDomainsDomainIdRoute
  '/w/$slug/imports/exports': typeof WSlugImportsExportsRoute
  '/w/$slug/imports/$importId': typeof WSlugImportsImportIdRoute
  '/w/$slug/imports/new': typeof WSlugImportsNewRoute
  '/w/$slug/inbox/$threadId': typeof WSlugInboxThreadIdRoute
  '/w/$slug/mailboxes/$connectionId': typeof WSlugMailboxesConnectionIdRouteWithChildren
  '/w/$slug/mailboxes/new': typeof WSlugMailboxesNewRoute
  '/w/$slug/messages/$messageId': typeof WSlugMessagesMessageIdRoute
  '/w/$slug/messages/new': typeof WSlugMessagesNewRoute
  '/w/$slug/people/$personId': typeof WSlugPeoplePersonIdRoute
  '/w/$slug/segments/$segmentId': typeof WSlugSegmentsSegmentIdRoute
  '/w/$slug/webhooks/$endpointId': typeof WSlugWebhooksEndpointIdRouteWithChildren
  '/w/$slug/campaigns/': typeof WSlugCampaignsIndexRoute
  '/w/$slug/domains/': typeof WSlugDomainsIndexRoute
  '/w/$slug/imports/': typeof WSlugImportsIndexRoute
  '/w/$slug/inbox/': typeof WSlugInboxIndexRoute
  '/w/$slug/mailboxes/': typeof WSlugMailboxesIndexRoute
  '/w/$slug/messages/': typeof WSlugMessagesIndexRoute
  '/w/$slug/people/': typeof WSlugPeopleIndexRoute
  '/w/$slug/segments/': typeof WSlugSegmentsIndexRoute
  '/w/$slug/webhooks/': typeof WSlugWebhooksIndexRoute
  '/w/$slug/campaigns/$campaignId/enrollments': typeof WSlugCampaignsCampaignIdEnrollmentsRoute
  '/w/$slug/campaigns/$campaignId/messages': typeof WSlugCampaignsCampaignIdMessagesRoute
  '/w/$slug/campaigns/$campaignId/sequence': typeof WSlugCampaignsCampaignIdSequenceRoute
  '/w/$slug/campaigns/$campaignId/settings': typeof WSlugCampaignsCampaignIdSettingsRoute
  '/w/$slug/inbox/received/$inboundId': typeof WSlugInboxReceivedInboundIdRoute
  '/w/$slug/mailboxes/$connectionId/settings': typeof WSlugMailboxesConnectionIdSettingsRoute
  '/w/$slug/webhooks/$endpointId/settings': typeof WSlugWebhooksEndpointIdSettingsRoute
  '/w/$slug/campaigns/$campaignId/': typeof WSlugCampaignsCampaignIdIndexRoute
  '/w/$slug/inbox/received/': typeof WSlugInboxReceivedIndexRoute
  '/w/$slug/mailboxes/$connectionId/': typeof WSlugMailboxesConnectionIdIndexRoute
  '/w/$slug/webhooks/$endpointId/': typeof WSlugWebhooksEndpointIdIndexRoute
}
export interface FileRoutesByTo {
  '/activate': typeof ActivateRoute
  '/new': typeof NewRoute
  '/account': typeof AccountAccountRoute
  '/workspaces': typeof AccountWorkspacesRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/sign-in/link': typeof SignInLinkRoute
  '/': typeof AccountIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/api-keys': typeof WSlugApiKeysRoute
  '/w/$slug/events': typeof WSlugEventsRoute
  '/w/$slug/fields': typeof WSlugFieldsRoute
  '/w/$slug/groups': typeof WSlugGroupsRoute
  '/w/$slug/logs': typeof WSlugLogsRoute
  '/w/$slug/preflight': typeof WSlugPreflightRoute
  '/w/$slug/quotas': typeof WSlugQuotasRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/suppressions': typeof WSlugSuppressionsRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/domains/$domainId': typeof WSlugDomainsDomainIdRoute
  '/w/$slug/imports/exports': typeof WSlugImportsExportsRoute
  '/w/$slug/imports/$importId': typeof WSlugImportsImportIdRoute
  '/w/$slug/imports/new': typeof WSlugImportsNewRoute
  '/w/$slug/inbox/$threadId': typeof WSlugInboxThreadIdRoute
  '/w/$slug/mailboxes/new': typeof WSlugMailboxesNewRoute
  '/w/$slug/messages/$messageId': typeof WSlugMessagesMessageIdRoute
  '/w/$slug/messages/new': typeof WSlugMessagesNewRoute
  '/w/$slug/people/$personId': typeof WSlugPeoplePersonIdRoute
  '/w/$slug/segments/$segmentId': typeof WSlugSegmentsSegmentIdRoute
  '/w/$slug/campaigns': typeof WSlugCampaignsIndexRoute
  '/w/$slug/domains': typeof WSlugDomainsIndexRoute
  '/w/$slug/imports': typeof WSlugImportsIndexRoute
  '/w/$slug/inbox': typeof WSlugInboxIndexRoute
  '/w/$slug/mailboxes': typeof WSlugMailboxesIndexRoute
  '/w/$slug/messages': typeof WSlugMessagesIndexRoute
  '/w/$slug/people': typeof WSlugPeopleIndexRoute
  '/w/$slug/segments': typeof WSlugSegmentsIndexRoute
  '/w/$slug/webhooks': typeof WSlugWebhooksIndexRoute
  '/w/$slug/campaigns/$campaignId/enrollments': typeof WSlugCampaignsCampaignIdEnrollmentsRoute
  '/w/$slug/campaigns/$campaignId/messages': typeof WSlugCampaignsCampaignIdMessagesRoute
  '/w/$slug/campaigns/$campaignId/sequence': typeof WSlugCampaignsCampaignIdSequenceRoute
  '/w/$slug/campaigns/$campaignId/settings': typeof WSlugCampaignsCampaignIdSettingsRoute
  '/w/$slug/inbox/received/$inboundId': typeof WSlugInboxReceivedInboundIdRoute
  '/w/$slug/mailboxes/$connectionId/settings': typeof WSlugMailboxesConnectionIdSettingsRoute
  '/w/$slug/webhooks/$endpointId/settings': typeof WSlugWebhooksEndpointIdSettingsRoute
  '/w/$slug/campaigns/$campaignId': typeof WSlugCampaignsCampaignIdIndexRoute
  '/w/$slug/inbox/received': typeof WSlugInboxReceivedIndexRoute
  '/w/$slug/mailboxes/$connectionId': typeof WSlugMailboxesConnectionIdIndexRoute
  '/w/$slug/webhooks/$endpointId': typeof WSlugWebhooksEndpointIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_account': typeof AccountRouteWithChildren
  '/activate': typeof ActivateRoute
  '/new': typeof NewRoute
  '/_account/account': typeof AccountAccountRoute
  '/_account/workspaces': typeof AccountWorkspacesRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/sign-in/link': typeof SignInLinkRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/_account/': typeof AccountIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/api-keys': typeof WSlugApiKeysRoute
  '/w/$slug/events': typeof WSlugEventsRoute
  '/w/$slug/fields': typeof WSlugFieldsRoute
  '/w/$slug/groups': typeof WSlugGroupsRoute
  '/w/$slug/imports': typeof WSlugImportsRouteWithChildren
  '/w/$slug/logs': typeof WSlugLogsRoute
  '/w/$slug/preflight': typeof WSlugPreflightRoute
  '/w/$slug/quotas': typeof WSlugQuotasRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/suppressions': typeof WSlugSuppressionsRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/campaigns/$campaignId': typeof WSlugCampaignsCampaignIdRouteWithChildren
  '/w/$slug/domains/$domainId': typeof WSlugDomainsDomainIdRoute
  '/w/$slug/imports/exports': typeof WSlugImportsExportsRoute
  '/w/$slug/imports_/$importId': typeof WSlugImportsImportIdRoute
  '/w/$slug/imports_/new': typeof WSlugImportsNewRoute
  '/w/$slug/inbox/$threadId': typeof WSlugInboxThreadIdRoute
  '/w/$slug/mailboxes/$connectionId': typeof WSlugMailboxesConnectionIdRouteWithChildren
  '/w/$slug/mailboxes/new': typeof WSlugMailboxesNewRoute
  '/w/$slug/messages/$messageId': typeof WSlugMessagesMessageIdRoute
  '/w/$slug/messages/new': typeof WSlugMessagesNewRoute
  '/w/$slug/people/$personId': typeof WSlugPeoplePersonIdRoute
  '/w/$slug/segments/$segmentId': typeof WSlugSegmentsSegmentIdRoute
  '/w/$slug/webhooks/$endpointId': typeof WSlugWebhooksEndpointIdRouteWithChildren
  '/w/$slug/campaigns/': typeof WSlugCampaignsIndexRoute
  '/w/$slug/domains/': typeof WSlugDomainsIndexRoute
  '/w/$slug/imports/': typeof WSlugImportsIndexRoute
  '/w/$slug/inbox/': typeof WSlugInboxIndexRoute
  '/w/$slug/mailboxes/': typeof WSlugMailboxesIndexRoute
  '/w/$slug/messages/': typeof WSlugMessagesIndexRoute
  '/w/$slug/people/': typeof WSlugPeopleIndexRoute
  '/w/$slug/segments/': typeof WSlugSegmentsIndexRoute
  '/w/$slug/webhooks/': typeof WSlugWebhooksIndexRoute
  '/w/$slug/campaigns/$campaignId/enrollments': typeof WSlugCampaignsCampaignIdEnrollmentsRoute
  '/w/$slug/campaigns/$campaignId/messages': typeof WSlugCampaignsCampaignIdMessagesRoute
  '/w/$slug/campaigns/$campaignId/sequence': typeof WSlugCampaignsCampaignIdSequenceRoute
  '/w/$slug/campaigns/$campaignId/settings': typeof WSlugCampaignsCampaignIdSettingsRoute
  '/w/$slug/inbox/received/$inboundId': typeof WSlugInboxReceivedInboundIdRoute
  '/w/$slug/mailboxes/$connectionId/settings': typeof WSlugMailboxesConnectionIdSettingsRoute
  '/w/$slug/webhooks/$endpointId/settings': typeof WSlugWebhooksEndpointIdSettingsRoute
  '/w/$slug/campaigns/$campaignId/': typeof WSlugCampaignsCampaignIdIndexRoute
  '/w/$slug/inbox/received/': typeof WSlugInboxReceivedIndexRoute
  '/w/$slug/mailboxes/$connectionId/': typeof WSlugMailboxesConnectionIdIndexRoute
  '/w/$slug/webhooks/$endpointId/': typeof WSlugWebhooksEndpointIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/new'
    | '/account'
    | '/workspaces'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/sign-in/link'
    | '/w/$slug'
    | '/sign-in/'
    | '/w/$slug/analytics'
    | '/w/$slug/api-keys'
    | '/w/$slug/events'
    | '/w/$slug/fields'
    | '/w/$slug/groups'
    | '/w/$slug/imports'
    | '/w/$slug/logs'
    | '/w/$slug/preflight'
    | '/w/$slug/quotas'
    | '/w/$slug/settings'
    | '/w/$slug/suppressions'
    | '/w/$slug/'
    | '/w/$slug/campaigns/$campaignId'
    | '/w/$slug/domains/$domainId'
    | '/w/$slug/imports/exports'
    | '/w/$slug/imports/$importId'
    | '/w/$slug/imports/new'
    | '/w/$slug/inbox/$threadId'
    | '/w/$slug/mailboxes/$connectionId'
    | '/w/$slug/mailboxes/new'
    | '/w/$slug/messages/$messageId'
    | '/w/$slug/messages/new'
    | '/w/$slug/people/$personId'
    | '/w/$slug/segments/$segmentId'
    | '/w/$slug/webhooks/$endpointId'
    | '/w/$slug/campaigns/'
    | '/w/$slug/domains/'
    | '/w/$slug/imports/'
    | '/w/$slug/inbox/'
    | '/w/$slug/mailboxes/'
    | '/w/$slug/messages/'
    | '/w/$slug/people/'
    | '/w/$slug/segments/'
    | '/w/$slug/webhooks/'
    | '/w/$slug/campaigns/$campaignId/enrollments'
    | '/w/$slug/campaigns/$campaignId/messages'
    | '/w/$slug/campaigns/$campaignId/sequence'
    | '/w/$slug/campaigns/$campaignId/settings'
    | '/w/$slug/inbox/received/$inboundId'
    | '/w/$slug/mailboxes/$connectionId/settings'
    | '/w/$slug/webhooks/$endpointId/settings'
    | '/w/$slug/campaigns/$campaignId/'
    | '/w/$slug/inbox/received/'
    | '/w/$slug/mailboxes/$connectionId/'
    | '/w/$slug/webhooks/$endpointId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate'
    | '/new'
    | '/account'
    | '/workspaces'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/sign-in/link'
    | '/'
    | '/sign-in'
    | '/w/$slug/analytics'
    | '/w/$slug/api-keys'
    | '/w/$slug/events'
    | '/w/$slug/fields'
    | '/w/$slug/groups'
    | '/w/$slug/logs'
    | '/w/$slug/preflight'
    | '/w/$slug/quotas'
    | '/w/$slug/settings'
    | '/w/$slug/suppressions'
    | '/w/$slug'
    | '/w/$slug/domains/$domainId'
    | '/w/$slug/imports/exports'
    | '/w/$slug/imports/$importId'
    | '/w/$slug/imports/new'
    | '/w/$slug/inbox/$threadId'
    | '/w/$slug/mailboxes/new'
    | '/w/$slug/messages/$messageId'
    | '/w/$slug/messages/new'
    | '/w/$slug/people/$personId'
    | '/w/$slug/segments/$segmentId'
    | '/w/$slug/campaigns'
    | '/w/$slug/domains'
    | '/w/$slug/imports'
    | '/w/$slug/inbox'
    | '/w/$slug/mailboxes'
    | '/w/$slug/messages'
    | '/w/$slug/people'
    | '/w/$slug/segments'
    | '/w/$slug/webhooks'
    | '/w/$slug/campaigns/$campaignId/enrollments'
    | '/w/$slug/campaigns/$campaignId/messages'
    | '/w/$slug/campaigns/$campaignId/sequence'
    | '/w/$slug/campaigns/$campaignId/settings'
    | '/w/$slug/inbox/received/$inboundId'
    | '/w/$slug/mailboxes/$connectionId/settings'
    | '/w/$slug/webhooks/$endpointId/settings'
    | '/w/$slug/campaigns/$campaignId'
    | '/w/$slug/inbox/received'
    | '/w/$slug/mailboxes/$connectionId'
    | '/w/$slug/webhooks/$endpointId'
  id:
    | '__root__'
    | '/_account'
    | '/activate'
    | '/new'
    | '/_account/account'
    | '/_account/workspaces'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/sign-in/link'
    | '/w/$slug'
    | '/_account/'
    | '/sign-in/'
    | '/w/$slug/analytics'
    | '/w/$slug/api-keys'
    | '/w/$slug/events'
    | '/w/$slug/fields'
    | '/w/$slug/groups'
    | '/w/$slug/imports'
    | '/w/$slug/logs'
    | '/w/$slug/preflight'
    | '/w/$slug/quotas'
    | '/w/$slug/settings'
    | '/w/$slug/suppressions'
    | '/w/$slug/'
    | '/w/$slug/campaigns/$campaignId'
    | '/w/$slug/domains/$domainId'
    | '/w/$slug/imports/exports'
    | '/w/$slug/imports_/$importId'
    | '/w/$slug/imports_/new'
    | '/w/$slug/inbox/$threadId'
    | '/w/$slug/mailboxes/$connectionId'
    | '/w/$slug/mailboxes/new'
    | '/w/$slug/messages/$messageId'
    | '/w/$slug/messages/new'
    | '/w/$slug/people/$personId'
    | '/w/$slug/segments/$segmentId'
    | '/w/$slug/webhooks/$endpointId'
    | '/w/$slug/campaigns/'
    | '/w/$slug/domains/'
    | '/w/$slug/imports/'
    | '/w/$slug/inbox/'
    | '/w/$slug/mailboxes/'
    | '/w/$slug/messages/'
    | '/w/$slug/people/'
    | '/w/$slug/segments/'
    | '/w/$slug/webhooks/'
    | '/w/$slug/campaigns/$campaignId/enrollments'
    | '/w/$slug/campaigns/$campaignId/messages'
    | '/w/$slug/campaigns/$campaignId/sequence'
    | '/w/$slug/campaigns/$campaignId/settings'
    | '/w/$slug/inbox/received/$inboundId'
    | '/w/$slug/mailboxes/$connectionId/settings'
    | '/w/$slug/webhooks/$endpointId/settings'
    | '/w/$slug/campaigns/$campaignId/'
    | '/w/$slug/inbox/received/'
    | '/w/$slug/mailboxes/$connectionId/'
    | '/w/$slug/webhooks/$endpointId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRoute: typeof AccountRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  NewRoute: typeof NewRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  OauthConsentRoute: typeof OauthConsentRoute
  SignInLinkRoute: typeof SignInLinkRoute
  WSlugRoute: typeof WSlugRouteWithChildren
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_account': {
      id: '/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_account/': {
      id: '/_account/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/account': {
      id: '/_account/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountAccountRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_account/workspaces': {
      id: '/_account/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AccountWorkspacesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/link': {
      id: '/sign-in/link'
      path: '/sign-in/link'
      fullPath: '/sign-in/link'
      preLoaderRoute: typeof SignInLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/analytics': {
      id: '/w/$slug/analytics'
      path: '/analytics'
      fullPath: '/w/$slug/analytics'
      preLoaderRoute: typeof WSlugAnalyticsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/api-keys': {
      id: '/w/$slug/api-keys'
      path: '/api-keys'
      fullPath: '/w/$slug/api-keys'
      preLoaderRoute: typeof WSlugApiKeysRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/events': {
      id: '/w/$slug/events'
      path: '/events'
      fullPath: '/w/$slug/events'
      preLoaderRoute: typeof WSlugEventsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/fields': {
      id: '/w/$slug/fields'
      path: '/fields'
      fullPath: '/w/$slug/fields'
      preLoaderRoute: typeof WSlugFieldsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/groups': {
      id: '/w/$slug/groups'
      path: '/groups'
      fullPath: '/w/$slug/groups'
      preLoaderRoute: typeof WSlugGroupsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/imports': {
      id: '/w/$slug/imports'
      path: '/imports'
      fullPath: '/w/$slug/imports'
      preLoaderRoute: typeof WSlugImportsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/logs': {
      id: '/w/$slug/logs'
      path: '/logs'
      fullPath: '/w/$slug/logs'
      preLoaderRoute: typeof WSlugLogsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/preflight': {
      id: '/w/$slug/preflight'
      path: '/preflight'
      fullPath: '/w/$slug/preflight'
      preLoaderRoute: typeof WSlugPreflightRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/quotas': {
      id: '/w/$slug/quotas'
      path: '/quotas'
      fullPath: '/w/$slug/quotas'
      preLoaderRoute: typeof WSlugQuotasRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/suppressions': {
      id: '/w/$slug/suppressions'
      path: '/suppressions'
      fullPath: '/w/$slug/suppressions'
      preLoaderRoute: typeof WSlugSuppressionsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/campaigns/': {
      id: '/w/$slug/campaigns/'
      path: '/campaigns'
      fullPath: '/w/$slug/campaigns/'
      preLoaderRoute: typeof WSlugCampaignsIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/campaigns/$campaignId': {
      id: '/w/$slug/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/w/$slug/campaigns/$campaignId'
      preLoaderRoute: typeof WSlugCampaignsCampaignIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/domains/': {
      id: '/w/$slug/domains/'
      path: '/domains'
      fullPath: '/w/$slug/domains/'
      preLoaderRoute: typeof WSlugDomainsIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/domains/$domainId': {
      id: '/w/$slug/domains/$domainId'
      path: '/domains/$domainId'
      fullPath: '/w/$slug/domains/$domainId'
      preLoaderRoute: typeof WSlugDomainsDomainIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/imports/': {
      id: '/w/$slug/imports/'
      path: '/'
      fullPath: '/w/$slug/imports/'
      preLoaderRoute: typeof WSlugImportsIndexRouteImport
      parentRoute: typeof WSlugImportsRoute
    }
    '/w/$slug/imports/exports': {
      id: '/w/$slug/imports/exports'
      path: '/exports'
      fullPath: '/w/$slug/imports/exports'
      preLoaderRoute: typeof WSlugImportsExportsRouteImport
      parentRoute: typeof WSlugImportsRoute
    }
    '/w/$slug/imports_/$importId': {
      id: '/w/$slug/imports_/$importId'
      path: '/imports/$importId'
      fullPath: '/w/$slug/imports/$importId'
      preLoaderRoute: typeof WSlugImportsImportIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/imports_/new': {
      id: '/w/$slug/imports_/new'
      path: '/imports/new'
      fullPath: '/w/$slug/imports/new'
      preLoaderRoute: typeof WSlugImportsNewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/inbox/': {
      id: '/w/$slug/inbox/'
      path: '/inbox'
      fullPath: '/w/$slug/inbox/'
      preLoaderRoute: typeof WSlugInboxIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/inbox/$threadId': {
      id: '/w/$slug/inbox/$threadId'
      path: '/inbox/$threadId'
      fullPath: '/w/$slug/inbox/$threadId'
      preLoaderRoute: typeof WSlugInboxThreadIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/mailboxes/': {
      id: '/w/$slug/mailboxes/'
      path: '/mailboxes'
      fullPath: '/w/$slug/mailboxes/'
      preLoaderRoute: typeof WSlugMailboxesIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/mailboxes/$connectionId': {
      id: '/w/$slug/mailboxes/$connectionId'
      path: '/mailboxes/$connectionId'
      fullPath: '/w/$slug/mailboxes/$connectionId'
      preLoaderRoute: typeof WSlugMailboxesConnectionIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/mailboxes/new': {
      id: '/w/$slug/mailboxes/new'
      path: '/mailboxes/new'
      fullPath: '/w/$slug/mailboxes/new'
      preLoaderRoute: typeof WSlugMailboxesNewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/messages/': {
      id: '/w/$slug/messages/'
      path: '/messages'
      fullPath: '/w/$slug/messages/'
      preLoaderRoute: typeof WSlugMessagesIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/messages/$messageId': {
      id: '/w/$slug/messages/$messageId'
      path: '/messages/$messageId'
      fullPath: '/w/$slug/messages/$messageId'
      preLoaderRoute: typeof WSlugMessagesMessageIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/messages/new': {
      id: '/w/$slug/messages/new'
      path: '/messages/new'
      fullPath: '/w/$slug/messages/new'
      preLoaderRoute: typeof WSlugMessagesNewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/people/': {
      id: '/w/$slug/people/'
      path: '/people'
      fullPath: '/w/$slug/people/'
      preLoaderRoute: typeof WSlugPeopleIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/people/$personId': {
      id: '/w/$slug/people/$personId'
      path: '/people/$personId'
      fullPath: '/w/$slug/people/$personId'
      preLoaderRoute: typeof WSlugPeoplePersonIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/segments/': {
      id: '/w/$slug/segments/'
      path: '/segments'
      fullPath: '/w/$slug/segments/'
      preLoaderRoute: typeof WSlugSegmentsIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/segments/$segmentId': {
      id: '/w/$slug/segments/$segmentId'
      path: '/segments/$segmentId'
      fullPath: '/w/$slug/segments/$segmentId'
      preLoaderRoute: typeof WSlugSegmentsSegmentIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/webhooks/': {
      id: '/w/$slug/webhooks/'
      path: '/webhooks'
      fullPath: '/w/$slug/webhooks/'
      preLoaderRoute: typeof WSlugWebhooksIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/webhooks/$endpointId': {
      id: '/w/$slug/webhooks/$endpointId'
      path: '/webhooks/$endpointId'
      fullPath: '/w/$slug/webhooks/$endpointId'
      preLoaderRoute: typeof WSlugWebhooksEndpointIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/campaigns/$campaignId/': {
      id: '/w/$slug/campaigns/$campaignId/'
      path: '/'
      fullPath: '/w/$slug/campaigns/$campaignId/'
      preLoaderRoute: typeof WSlugCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof WSlugCampaignsCampaignIdRoute
    }
    '/w/$slug/campaigns/$campaignId/enrollments': {
      id: '/w/$slug/campaigns/$campaignId/enrollments'
      path: '/enrollments'
      fullPath: '/w/$slug/campaigns/$campaignId/enrollments'
      preLoaderRoute: typeof WSlugCampaignsCampaignIdEnrollmentsRouteImport
      parentRoute: typeof WSlugCampaignsCampaignIdRoute
    }
    '/w/$slug/campaigns/$campaignId/messages': {
      id: '/w/$slug/campaigns/$campaignId/messages'
      path: '/messages'
      fullPath: '/w/$slug/campaigns/$campaignId/messages'
      preLoaderRoute: typeof WSlugCampaignsCampaignIdMessagesRouteImport
      parentRoute: typeof WSlugCampaignsCampaignIdRoute
    }
    '/w/$slug/campaigns/$campaignId/sequence': {
      id: '/w/$slug/campaigns/$campaignId/sequence'
      path: '/sequence'
      fullPath: '/w/$slug/campaigns/$campaignId/sequence'
      preLoaderRoute: typeof WSlugCampaignsCampaignIdSequenceRouteImport
      parentRoute: typeof WSlugCampaignsCampaignIdRoute
    }
    '/w/$slug/campaigns/$campaignId/settings': {
      id: '/w/$slug/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/w/$slug/campaigns/$campaignId/settings'
      preLoaderRoute: typeof WSlugCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof WSlugCampaignsCampaignIdRoute
    }
    '/w/$slug/inbox/received/': {
      id: '/w/$slug/inbox/received/'
      path: '/inbox/received'
      fullPath: '/w/$slug/inbox/received/'
      preLoaderRoute: typeof WSlugInboxReceivedIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/inbox/received/$inboundId': {
      id: '/w/$slug/inbox/received/$inboundId'
      path: '/inbox/received/$inboundId'
      fullPath: '/w/$slug/inbox/received/$inboundId'
      preLoaderRoute: typeof WSlugInboxReceivedInboundIdRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/mailboxes/$connectionId/': {
      id: '/w/$slug/mailboxes/$connectionId/'
      path: '/'
      fullPath: '/w/$slug/mailboxes/$connectionId/'
      preLoaderRoute: typeof WSlugMailboxesConnectionIdIndexRouteImport
      parentRoute: typeof WSlugMailboxesConnectionIdRoute
    }
    '/w/$slug/mailboxes/$connectionId/settings': {
      id: '/w/$slug/mailboxes/$connectionId/settings'
      path: '/settings'
      fullPath: '/w/$slug/mailboxes/$connectionId/settings'
      preLoaderRoute: typeof WSlugMailboxesConnectionIdSettingsRouteImport
      parentRoute: typeof WSlugMailboxesConnectionIdRoute
    }
    '/w/$slug/webhooks/$endpointId/': {
      id: '/w/$slug/webhooks/$endpointId/'
      path: '/'
      fullPath: '/w/$slug/webhooks/$endpointId/'
      preLoaderRoute: typeof WSlugWebhooksEndpointIdIndexRouteImport
      parentRoute: typeof WSlugWebhooksEndpointIdRoute
    }
    '/w/$slug/webhooks/$endpointId/settings': {
      id: '/w/$slug/webhooks/$endpointId/settings'
      path: '/settings'
      fullPath: '/w/$slug/webhooks/$endpointId/settings'
      preLoaderRoute: typeof WSlugWebhooksEndpointIdSettingsRouteImport
      parentRoute: typeof WSlugWebhooksEndpointIdRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAccountRoute: typeof AccountAccountRoute
  AccountWorkspacesRoute: typeof AccountWorkspacesRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAccountRoute: AccountAccountRoute,
  AccountWorkspacesRoute: AccountWorkspacesRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface WSlugImportsRouteChildren {
  WSlugImportsExportsRoute: typeof WSlugImportsExportsRoute
  WSlugImportsIndexRoute: typeof WSlugImportsIndexRoute
}

const WSlugImportsRouteChildren: WSlugImportsRouteChildren = {
  WSlugImportsExportsRoute: WSlugImportsExportsRoute,
  WSlugImportsIndexRoute: WSlugImportsIndexRoute,
}

const WSlugImportsRouteWithChildren = WSlugImportsRoute._addFileChildren(
  WSlugImportsRouteChildren,
)

interface WSlugCampaignsCampaignIdRouteChildren {
  WSlugCampaignsCampaignIdEnrollmentsRoute: typeof WSlugCampaignsCampaignIdEnrollmentsRoute
  WSlugCampaignsCampaignIdMessagesRoute: typeof WSlugCampaignsCampaignIdMessagesRoute
  WSlugCampaignsCampaignIdSequenceRoute: typeof WSlugCampaignsCampaignIdSequenceRoute
  WSlugCampaignsCampaignIdSettingsRoute: typeof WSlugCampaignsCampaignIdSettingsRoute
  WSlugCampaignsCampaignIdIndexRoute: typeof WSlugCampaignsCampaignIdIndexRoute
}

const WSlugCampaignsCampaignIdRouteChildren: WSlugCampaignsCampaignIdRouteChildren =
  {
    WSlugCampaignsCampaignIdEnrollmentsRoute:
      WSlugCampaignsCampaignIdEnrollmentsRoute,
    WSlugCampaignsCampaignIdMessagesRoute:
      WSlugCampaignsCampaignIdMessagesRoute,
    WSlugCampaignsCampaignIdSequenceRoute:
      WSlugCampaignsCampaignIdSequenceRoute,
    WSlugCampaignsCampaignIdSettingsRoute:
      WSlugCampaignsCampaignIdSettingsRoute,
    WSlugCampaignsCampaignIdIndexRoute: WSlugCampaignsCampaignIdIndexRoute,
  }

const WSlugCampaignsCampaignIdRouteWithChildren =
  WSlugCampaignsCampaignIdRoute._addFileChildren(
    WSlugCampaignsCampaignIdRouteChildren,
  )

interface WSlugMailboxesConnectionIdRouteChildren {
  WSlugMailboxesConnectionIdSettingsRoute: typeof WSlugMailboxesConnectionIdSettingsRoute
  WSlugMailboxesConnectionIdIndexRoute: typeof WSlugMailboxesConnectionIdIndexRoute
}

const WSlugMailboxesConnectionIdRouteChildren: WSlugMailboxesConnectionIdRouteChildren =
  {
    WSlugMailboxesConnectionIdSettingsRoute:
      WSlugMailboxesConnectionIdSettingsRoute,
    WSlugMailboxesConnectionIdIndexRoute: WSlugMailboxesConnectionIdIndexRoute,
  }

const WSlugMailboxesConnectionIdRouteWithChildren =
  WSlugMailboxesConnectionIdRoute._addFileChildren(
    WSlugMailboxesConnectionIdRouteChildren,
  )

interface WSlugWebhooksEndpointIdRouteChildren {
  WSlugWebhooksEndpointIdSettingsRoute: typeof WSlugWebhooksEndpointIdSettingsRoute
  WSlugWebhooksEndpointIdIndexRoute: typeof WSlugWebhooksEndpointIdIndexRoute
}

const WSlugWebhooksEndpointIdRouteChildren: WSlugWebhooksEndpointIdRouteChildren =
  {
    WSlugWebhooksEndpointIdSettingsRoute: WSlugWebhooksEndpointIdSettingsRoute,
    WSlugWebhooksEndpointIdIndexRoute: WSlugWebhooksEndpointIdIndexRoute,
  }

const WSlugWebhooksEndpointIdRouteWithChildren =
  WSlugWebhooksEndpointIdRoute._addFileChildren(
    WSlugWebhooksEndpointIdRouteChildren,
  )

interface WSlugRouteChildren {
  WSlugAnalyticsRoute: typeof WSlugAnalyticsRoute
  WSlugApiKeysRoute: typeof WSlugApiKeysRoute
  WSlugEventsRoute: typeof WSlugEventsRoute
  WSlugFieldsRoute: typeof WSlugFieldsRoute
  WSlugGroupsRoute: typeof WSlugGroupsRoute
  WSlugImportsRoute: typeof WSlugImportsRouteWithChildren
  WSlugLogsRoute: typeof WSlugLogsRoute
  WSlugPreflightRoute: typeof WSlugPreflightRoute
  WSlugQuotasRoute: typeof WSlugQuotasRoute
  WSlugSettingsRoute: typeof WSlugSettingsRoute
  WSlugSuppressionsRoute: typeof WSlugSuppressionsRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
  WSlugCampaignsCampaignIdRoute: typeof WSlugCampaignsCampaignIdRouteWithChildren
  WSlugDomainsDomainIdRoute: typeof WSlugDomainsDomainIdRoute
  WSlugImportsImportIdRoute: typeof WSlugImportsImportIdRoute
  WSlugImportsNewRoute: typeof WSlugImportsNewRoute
  WSlugInboxThreadIdRoute: typeof WSlugInboxThreadIdRoute
  WSlugMailboxesConnectionIdRoute: typeof WSlugMailboxesConnectionIdRouteWithChildren
  WSlugMailboxesNewRoute: typeof WSlugMailboxesNewRoute
  WSlugMessagesMessageIdRoute: typeof WSlugMessagesMessageIdRoute
  WSlugMessagesNewRoute: typeof WSlugMessagesNewRoute
  WSlugPeoplePersonIdRoute: typeof WSlugPeoplePersonIdRoute
  WSlugSegmentsSegmentIdRoute: typeof WSlugSegmentsSegmentIdRoute
  WSlugWebhooksEndpointIdRoute: typeof WSlugWebhooksEndpointIdRouteWithChildren
  WSlugCampaignsIndexRoute: typeof WSlugCampaignsIndexRoute
  WSlugDomainsIndexRoute: typeof WSlugDomainsIndexRoute
  WSlugInboxIndexRoute: typeof WSlugInboxIndexRoute
  WSlugMailboxesIndexRoute: typeof WSlugMailboxesIndexRoute
  WSlugMessagesIndexRoute: typeof WSlugMessagesIndexRoute
  WSlugPeopleIndexRoute: typeof WSlugPeopleIndexRoute
  WSlugSegmentsIndexRoute: typeof WSlugSegmentsIndexRoute
  WSlugWebhooksIndexRoute: typeof WSlugWebhooksIndexRoute
  WSlugInboxReceivedInboundIdRoute: typeof WSlugInboxReceivedInboundIdRoute
  WSlugInboxReceivedIndexRoute: typeof WSlugInboxReceivedIndexRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugAnalyticsRoute: WSlugAnalyticsRoute,
  WSlugApiKeysRoute: WSlugApiKeysRoute,
  WSlugEventsRoute: WSlugEventsRoute,
  WSlugFieldsRoute: WSlugFieldsRoute,
  WSlugGroupsRoute: WSlugGroupsRoute,
  WSlugImportsRoute: WSlugImportsRouteWithChildren,
  WSlugLogsRoute: WSlugLogsRoute,
  WSlugPreflightRoute: WSlugPreflightRoute,
  WSlugQuotasRoute: WSlugQuotasRoute,
  WSlugSettingsRoute: WSlugSettingsRoute,
  WSlugSuppressionsRoute: WSlugSuppressionsRoute,
  WSlugIndexRoute: WSlugIndexRoute,
  WSlugCampaignsCampaignIdRoute: WSlugCampaignsCampaignIdRouteWithChildren,
  WSlugDomainsDomainIdRoute: WSlugDomainsDomainIdRoute,
  WSlugImportsImportIdRoute: WSlugImportsImportIdRoute,
  WSlugImportsNewRoute: WSlugImportsNewRoute,
  WSlugInboxThreadIdRoute: WSlugInboxThreadIdRoute,
  WSlugMailboxesConnectionIdRoute: WSlugMailboxesConnectionIdRouteWithChildren,
  WSlugMailboxesNewRoute: WSlugMailboxesNewRoute,
  WSlugMessagesMessageIdRoute: WSlugMessagesMessageIdRoute,
  WSlugMessagesNewRoute: WSlugMessagesNewRoute,
  WSlugPeoplePersonIdRoute: WSlugPeoplePersonIdRoute,
  WSlugSegmentsSegmentIdRoute: WSlugSegmentsSegmentIdRoute,
  WSlugWebhooksEndpointIdRoute: WSlugWebhooksEndpointIdRouteWithChildren,
  WSlugCampaignsIndexRoute: WSlugCampaignsIndexRoute,
  WSlugDomainsIndexRoute: WSlugDomainsIndexRoute,
  WSlugInboxIndexRoute: WSlugInboxIndexRoute,
  WSlugMailboxesIndexRoute: WSlugMailboxesIndexRoute,
  WSlugMessagesIndexRoute: WSlugMessagesIndexRoute,
  WSlugPeopleIndexRoute: WSlugPeopleIndexRoute,
  WSlugSegmentsIndexRoute: WSlugSegmentsIndexRoute,
  WSlugWebhooksIndexRoute: WSlugWebhooksIndexRoute,
  WSlugInboxReceivedInboundIdRoute: WSlugInboxReceivedInboundIdRoute,
  WSlugInboxReceivedIndexRoute: WSlugInboxReceivedIndexRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AccountRoute: AccountRouteWithChildren,
  ActivateRoute: ActivateRoute,
  NewRoute: NewRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  OauthConsentRoute: OauthConsentRoute,
  SignInLinkRoute: SignInLinkRoute,
  WSlugRoute: WSlugRouteWithChildren,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
