/**
 * Regenerates `src/generated/` from the Norbelys OpenAPI contract.
 *
 *   bun run generate                                               # the committed public OpenAPI contract
 *   bun run generate --spec https://api.norbelys.com/openapi.json  # the document a deployment serves
 *   bun run generate --spec ./openapi.json                         # an explicit file, not the repository task
 *
 * `schema.ts` holds the types, written by a pinned openapi-typescript. It runs isolated through
 * `bun x` with the TypeScript API it needs; the SDK itself compiles with TypeScript 7, whose native
 * compiler no longer ships that API. `resources.ts` holds one method per operation, named from its
 * dotted operationId in camelCase: `webhook_endpoints.rotate_secret` becomes
 * `norbelys.webhookEndpoints.rotateSecret()`. A method answers every success its operation
 * declares (a union when there are several, `undefined` for one without a body), and an update
 * that takes `If-Match` accepts the `ifMatch` option. Unknown shapes fail loudly instead of
 * generating guesses: fix the contract in Rust rather than special-casing it here.
 */
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { parseArgs } from "node:util";

import {
  loadContract,
  operationEntries,
} from "../../../tools/codegen/contract";
import type {
  Answer,
  HttpMethod,
  Operation,
  Parameter,
  Reference,
  Spec,
} from "../../../tools/codegen/contract";

export type { Spec } from "../../../tools/codegen/contract";

const OPENAPI_TYPESCRIPT = "openapi-typescript@7.13.0";

interface Method {
  name: string;
  operationId: string;
  httpMethod: HttpMethod;
  path: string;
  operation: Operation;
}

interface Resource {
  segments: string[];
  methods: Method[];
  children: Map<string, Resource>;
}

const HEADER =
  "// Generated by scripts/generate.ts from the Norbelys OpenAPI contract. Do not edit.\n\n";
const OUT_DIR = new URL("../src/generated/", import.meta.url);

const camel = (value: string): string =>
  value.replaceAll(/[_-](?<letter>[a-z0-9])/gu, (_match, letter: string) =>
    letter.toUpperCase()
  );

const className = (segments: string[]): string =>
  segments.length === 0
    ? "NorbelysResources"
    : segments
        .map((segment) => camel(segment).replace(/^./u, (c) => c.toUpperCase()))
        .join("");

const insert = (top: Resource, method: Method, segments: string[]): void => {
  let node = top;
  for (const segment of segments) {
    let child = node.children.get(segment);
    if (!child) {
      child = {
        segments: [...node.segments, segment],
        methods: [],
        children: new Map(),
      };
      node.children.set(segment, child);
    }
    node = child;
  }
  node.methods.push(method);
};

const tree = (document: Spec): Resource => {
  const top: Resource = { segments: [], methods: [], children: new Map() };
  for (const entry of operationEntries(document)) {
    insert(
      top,
      {
        name: camel(entry.action),
        operationId: entry.operationId,
        httpMethod: entry.httpMethod,
        path: entry.path,
        operation: entry.operation,
      },
      entry.segments
    );
  }
  return top;
};

const SCHEMA_REF = /^#\/components\/schemas\/(?<name>[A-Za-z_$][\w$]*)$/u;

/** The exported alias of a component schema, such as `schema.Person`. */
const aliasOf = (reference: Reference | undefined): string | undefined => {
  const name = reference?.$ref?.match(SCHEMA_REF)?.groups?.name;
  return name === undefined ? undefined : `schema.${name}`;
};

const componentOf = (
  document: Spec,
  reference: Reference | undefined
): Record<string, unknown> | undefined => {
  const name = reference?.$ref?.match(SCHEMA_REF)?.groups?.name;
  return name === undefined ? undefined : document.components?.schemas?.[name];
};

/** Text for a JSDoc comment: the text is Markdown, so only a comment terminator needs escaping. */
const escapeDoc = (text: string): string => text.replaceAll("*/", "*\\/");

/** One line of a JSDoc tag: the text's whitespace collapsed, since a tag holds one line. */
const docLine = (text: string): string =>
  escapeDoc(text).replaceAll(/\s+/gu, " ").trim();

/** JSDoc lines: paragraphs separated by blank lines, then the tags, one per line. */
const docComment = (paragraphs: string[], tags: string[] = []): string[] => [
  "  /**",
  ...[
    ...paragraphs.flatMap((paragraph, index) => [
      ...(index > 0 ? [""] : []),
      ...escapeDoc(paragraph.trim()).split("\n"),
    ]),
    ...(tags.length > 0 ? ["", ...tags] : []),
  ].map((line) => (line ? `   * ${line.trimEnd()}` : "   *")),
  "   */",
];

/** A property signature for a JSON-valued query parameter. */
const jsonQueryMember = (method: Method, parameter: Parameter): string => {
  const media = Object.keys(parameter.content ?? {});
  const type = aliasOf(parameter.content?.["application/json"]?.schema);
  if (media.length !== 1 || type === undefined) {
    throw new Error(
      `${method.operationId}: query parameter ${parameter.name} must be JSON with a schema reference.`
    );
  }
  const doc = parameter.description
    ? `/** ${docLine(parameter.description)} */ `
    : "";
  return `${doc}${parameter.name}${parameter.required ? "" : "?"}: ${type}`;
};

/** The type of one success answer's body: `undefined` when it has none. */
const answerType = (
  operationId: string,
  status: string,
  answer: Answer
): string => {
  const media = Object.keys(answer.content ?? {});
  if (media.length === 0) {
    return "undefined";
  }
  const json = answer.content?.["application/json"];
  if (media.length > 1 || json === undefined) {
    throw new Error(
      `${operationId}: unsupported ${status} response media ${media.join(", ")}.`
    );
  }
  return (
    aliasOf(json.schema) ??
    `operations["${operationId}"]["responses"][${status}]["content"]["application/json"]`
  );
};

/**
 * What a method resolves to: the union of every success the operation declares, a bodiless one
 * last as `undefined` (`CampaignObject | undefined`), or `void` when none has a body.
 */
const resultOf = (
  method: Method
): { result: string; successes: [string, Answer][] } => {
  const successes = Object.entries(method.operation.responses).filter(
    ([status]) => status.startsWith("2")
  );
  if (successes.length === 0) {
    throw new Error(`${method.operationId}: no 2xx response.`);
  }
  const types = [
    ...new Set(
      successes.map(([status, answer]) =>
        answerType(method.operationId, status, answer)
      )
    ),
  ];
  const bodies = types.filter((type) => type !== "undefined");
  if (bodies.length === 0) {
    return { result: "void", successes };
  }
  return {
    result: [
      ...bodies,
      ...(bodies.length < types.length ? ["undefined"] : []),
    ].join(" | "),
    successes,
  };
};

/** The JSDoc lines of an operation with several successes: each status and what it means. */
const successDoc = (method: Method, successes: [string, Answer][]): string[] =>
  successes.length < 2
    ? []
    : [
        [
          "Answers one of:",
          ...successes.map(([status, answer]) => {
            const type = answerType(method.operationId, status, answer);
            const shown =
              type === "undefined"
                ? "no body, `undefined`"
                : `\`${type.replace(/^schema\./u, "")}\``;
            const meaning = answer.description
              ? `: ${docLine(answer.description)}`
              : "";
            return `- \`${status}\` (${shown})${meaning}`;
          }),
        ].join("\n"),
      ];

/** Body media and any accompanying query parameters share one generated call. */
const bodyInput = (
  document: Spec,
  method: Method,
  body: NonNullable<Operation["requestBody"]>,
  query: Parameter[]
): { args: string[]; input: string; body?: string } => {
  const op = `operations["${method.operationId}"]`;
  const queryArgs =
    query.length > 0
      ? [
          `query${query.every((p) => !p.required) ? "?" : ""}: NonNullable<${op}["parameters"]["query"]>`,
        ]
      : [];
  const queryInput = query.length > 0 ? ", query" : "";
  const media = Object.keys(body.content ?? {});
  if (media.every((type) => type.startsWith("image/")) && media.length > 0) {
    return {
      args: [
        `body: { data: Blob; contentType: ${media.map((type) => JSON.stringify(type)).join(" | ")} }`,
        ...queryArgs,
      ],
      input: `{ rawBody: body.data, contentType: body.contentType${queryInput} }`,
    };
  }
  if (
    media.some((type) => type !== "application/json" && type !== "text/csv")
  ) {
    throw new Error(
      `${method.operationId}: unsupported request media ${media.join(", ")}.`
    );
  }
  const reference = body.content?.["application/json"]?.schema;
  const type =
    aliasOf(reference) ??
    `NonNullable<${op}["requestBody"]>["content"]["application/json"]`;
  const component = componentOf(document, reference);
  // A body that is a union of closed forms accepts exactly one of them.
  const union =
    component !== undefined && ("oneOf" in component || "anyOf" in component);
  return {
    args: [
      `body${body.required ? "" : "?"}: ${union ? `OneOf<${type}>` : type}${media.includes("text/csv") ? " | string" : ""}`,
      ...queryArgs,
    ],
    input: media.includes("text/csv")
      ? `typeof body === "string" ? { rawBody: body, contentType: "text/csv"${queryInput} } : { body${queryInput} }`
      : `{ body${queryInput} }`,
    body: type,
  };
};

/** The method's parameter list after its path arguments, and the matching request input. */
const methodInput = (
  document: Spec,
  method: Method,
  paginated: boolean
): { args: string[]; input: string; body?: string } => {
  const op = `operations["${method.operationId}"]`;
  const body = method.operation.requestBody;
  const query = (method.operation.parameters ?? []).filter(
    (p) => p.in === "query"
  );
  if (body) {
    return bodyInput(document, method, body, query);
  }
  if (query.length === 0) {
    return { args: [], input: "{}" };
  }
  const optional = query.every((p) => !p.required || p.name === "cursor")
    ? "?"
    : "";
  const json = query.filter((p) => p.content !== undefined);
  const omitted = json.map((p) => p.name);
  const base = `NonNullable<${op}["parameters"]["query"]>`;
  const type = [
    omitted.length > 0
      ? `Omit<${base}, ${omitted.map((name) => `"${name}"`).join(" | ")}>`
      : base,
    ...(json.length > 0
      ? [`{ ${json.map((p) => jsonQueryMember(method, p)).join("; ")} }`]
      : []),
  ].join(" & ");
  return {
    args: [`query${optional}: ${type}`],
    // A list starts at `query.cursor`; `PagePromise` passes the cursor of each following page.
    input: paginated
      ? "{ query: { ...query, cursor: cursor ?? query?.cursor } }"
      : "{ query }",
  };
};

const emitMethod = (document: Spec, method: Method): string[] => {
  const { operation, operationId } = method;
  const parameters = operation.parameters ?? [];
  const unsupported = parameters.filter(
    (p) =>
      p.in === "cookie" ||
      (p.in === "header" &&
        p.name !== "Idempotency-Key" &&
        p.name !== "If-Match") ||
      (p.in !== "query" && p.content !== undefined)
  );
  if (unsupported.length > 0) {
    throw new Error(
      `${operationId}: unsupported parameters ${unsupported.map((p) => p.name).join(", ")}.`
    );
  }
  const { result, successes } = resultOf(method);
  const lists = parameters.some((p) => p.in === "query" && p.name === "cursor");
  if (lists && successes.length > 1) {
    throw new Error(`${operationId}: a list answers one success.`);
  }
  const paginated = lists && result !== "void";
  const idempotent = parameters.some(
    (p) => p.in === "header" && p.name === "Idempotency-Key"
  );
  // An update guarded by `If-Match` takes the version it was prepared from as `ifMatch`.
  const conditional = parameters.some(
    (p) => p.in === "header" && p.name === "If-Match"
  );
  const pathParameters = parameters.filter((p) => p.in === "path");
  const pathNames = [...method.path.matchAll(/\{(?<name>[^}]+)\}/gu)].map(
    (match) => match.groups?.name ?? ""
  );
  const { args, input, body } = methodInput(document, method, paginated);
  const signature = (inputArgs: string[]): string =>
    [
      ...pathNames.map((name) => `${camel(name)}: string`),
      ...inputArgs,
      `options?: ${conditional ? "UpdateOptions" : "RequestOptions"}`,
    ].join(", ");

  const verb = method.httpMethod.toUpperCase();
  const route = `{ method: "${verb}", path: "${method.path}", idempotent: ${idempotent} }`;
  const call = (requestOptions: string): string =>
    `this.#core.request<${result}>(${route}, [${pathNames.map(camel).join(", ")}], ${input}, ${requestOptions})`;
  const doc = docComment(
    [
      operation.summary ?? operationId,
      ...(operation.description ? [operation.description] : []),
      ...successDoc(method, successes),
      `\`${verb} ${method.path}\``,
    ],
    pathNames.map((name) => {
      const described = pathParameters.find(
        (p) => p.name === name
      )?.description;
      return `@param ${camel(name)}${described ? ` - ${docLine(described)}` : ""}`;
    })
  );
  const returns = paginated ? `PagePromise<${result}>` : `Promise<${result}>`;
  const implementation = (bodyArgs: string[]): string[] => [
    `  ${method.name}(${signature(bodyArgs)}): ${returns} {`,
    paginated
      ? `    return new PagePromise((cursor, pageOptions) => ${call("{ ...options, ...pageOptions }")});`
      : `    return ${call("options")};`,
    "  }",
  ];
  const overloads = operation["x-norbelys-overloads"];
  if (overloads === undefined) {
    return [...doc, ...implementation(args)];
  }
  if (body === undefined || paginated) {
    throw new Error(`${operationId}: overloads need a request body.`);
  }
  // One signature per answer, listing every request form that receives it.
  const forms = new Map<string, string[]>();
  for (const { request, response } of overloads) {
    const requestType = aliasOf(request);
    const responseType = aliasOf(response);
    if (requestType === undefined || responseType === undefined) {
      throw new Error(
        `${operationId}: overloads must reference component schemas.`
      );
    }
    forms.set(responseType, [...(forms.get(responseType) ?? []), requestType]);
  }
  return [
    ...[...forms].flatMap(([responseType, requests]) => [
      ...doc,
      `  ${method.name}(${signature([`body: OneOf<${body}, ${requests.join(" | ")}>`])}): Promise<${responseType}>;`,
    ]),
    ...doc,
    `  ${method.name}(${signature([`body: OneOf<${body}>`])}): ${returns};`,
    ...implementation([`body: ${body}`]),
  ];
};

const emitResource = (document: Spec, node: Resource, out: string[]): void => {
  for (const child of node.children.values()) {
    emitResource(document, child, out);
  }
  const fields = [...node.children].map(
    ([segment, child]) =>
      `  readonly ${camel(segment)}: ${className(child.segments)};`
  );
  const assignments = [...node.children].map(
    ([segment, child]) =>
      `    this.${camel(segment)} = new ${className(child.segments)}(core);`
  );
  const hasMethods = node.methods.length > 0;
  out.push(
    [
      node.segments.length > 0
        ? `/** \`${node.segments.join(".")}\` */`
        : "/** Every Norbelys resource. */",
      `export class ${className(node.segments)} {`,
      ...fields,
      ...(hasMethods ? ["  readonly #core: Core;"] : []),
      "",
      "  constructor(core: Core) {",
      ...(hasMethods ? ["    this.#core = core;"] : []),
      ...assignments,
      "  }",
      ...node.methods.flatMap((method) => [
        "",
        ...emitMethod(document, method),
      ]),
      "}",
      "",
    ].join("\n")
  );
};

const count = (node: Resource): number =>
  node.methods.length +
  [...node.children.values()].reduce((sum, child) => sum + count(child), 0);

/** Writes `schema.ts` with every path, operation and schema type, plus one alias per schema. */
const writeTypes = async (document: Spec): Promise<string> => {
  const dir = await mkdtemp(path.join(tmpdir(), "norbelys-sdk-"));
  try {
    const input = path.join(dir, "openapi.json");
    await writeFile(input, JSON.stringify(document));
    const output = path.join(dir, "schema.ts");
    const flags = [
      "--root-types",
      "--root-types-no-schema-prefix",
      "--root-types-keep-casing",
      // A default makes a request member optional; openapi-typescript would require it.
      "--default-non-nullable=false",
      // Arbitrary JSON maps (template variables and custom fields) have no fixed properties.
      "--empty-objects-unknown",
    ];
    const result = Bun.spawnSync(
      [
        process.execPath,
        "x",
        OPENAPI_TYPESCRIPT,
        input,
        "--output",
        output,
        ...flags,
      ],
      { stdout: "ignore", stderr: "inherit" }
    );
    if (!result.success) {
      throw new Error(`${OPENAPI_TYPESCRIPT} failed.`);
    }
    return await readFile(output, "utf-8");
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
};

/** The source of `resources.ts` for a contract, and how many methods it holds. */
export const generateResources = (
  document: Spec
): { code: string; methods: number } => {
  const root = tree(document);
  const classes: string[] = [];
  emitResource(document, root, classes);
  // Only what the methods use: the SDK compiles with `noUnusedLocals`.
  const helpers = ["Core", "OneOf", "RequestOptions", "UpdateOptions"].filter(
    (name) =>
      name === "Core" ||
      name === "RequestOptions" ||
      classes.some(
        (source) => source.includes(`${name}<`) || source.includes(`: ${name}`)
      )
  );
  const code = [
    HEADER.trimEnd(),
    `import type { ${helpers.join(", ")} } from "../core";`,
    'import { PagePromise } from "../pagination";',
    'import type * as schema from "./schema";',
    'import type { operations } from "./schema";',
    "",
    ...classes,
  ].join("\n");
  return { code, methods: count(root) };
};

if (import.meta.main) {
  const { values } = parseArgs({
    options: {
      spec: { type: "string" },
      check: { type: "boolean", default: false },
    },
  });
  const spec = await loadContract(values.spec);
  const { code, methods } = generateResources(spec);
  const files = { "schema.ts": await writeTypes(spec), "resources.ts": code };
  if (!values.check) {
    await mkdir(OUT_DIR, { recursive: true });
  }
  await Promise.all(
    Object.entries(files).map(async ([name, content]) => {
      const output = new URL(name, OUT_DIR);
      if (values.check) {
        if (
          !(await Bun.file(output).exists()) ||
          (await Bun.file(output).text()) !== content
        ) {
          throw new Error(
            `${name} differs from the public contract; run generate.`
          );
        }
      } else {
        await writeFile(output, content);
      }
    })
  );
  process.stdout.write(
    `${
      (values.check ? "Verified " : "Generated ") + methods
    } methods from the public contract.\n`
  );
}
