/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: f4b80cf17903075dcb688c43179b9043)
interface __BaseEnv_Env {
	API_ORIGIN: string;
	DASHBOARD_ORIGIN: string;
	OTEL_EXPORTER_OTLP_ENDPOINT: string;
	NORBELYS_TRACE_SAMPLE_PERCENT: string;
	PRODUCT_RELEASE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_ORIGIN" | "DASHBOARD_ORIGIN" | "OTEL_EXPORTER_OTLP_ENDPOINT" | "NORBELYS_TRACE_SAMPLE_PERCENT" | "PRODUCT_RELEASE">> {}
}
