//! The decisions behind counters and the data lifecycle: what the rollup may count, which days
//! the nightly recount owns, when a partition leaf may leave the database, in which order the
//! leaves of one period are archived, and what an analytics query may ask for.
//!
//! # Counting with a lag
//!
//! Every counted fact writes one `stats_increments` row in the transaction that produces it,
//! with an id generated by the database (UUIDv7: unix milliseconds in the top 48 bits, so the
//! smallest id of an instant is [`uuidv7_boundary`]). Ids are taken when the row is written,
//! not when its transaction commits, so "the newest id seen" is not a safe watermark: a slow
//! transaction can commit a smaller id after a larger one was counted. The rollup therefore
//! counts only ids below the boundary of `now − ROLLUP_LAG`, where the lag is twice the longest
//! `transaction_timeout` of any role allowed to write increments (60 s): by then every
//! transaction that could hold such an id has committed or aborted. The watermark only moves
//! forward ([`drain_range`]).
//!
//! # The nightly recount
//!
//! The recount reconciles each finished UTC day from the increments still online and marks it
//! verified. It owns every day after the last one it recorded, up to yesterday, so a missed
//! night is caught up rather than skipped ([`recount_days`]); the catch-up is bounded, since
//! increments older than their partition's retention are gone anyway.
//!
//! # Leaving the database
//!
//! The time-partitioned tables keep a period online for their retention, then the period's
//! leaf is detached, sealed, exported to Parquet when the table is archived, and dropped. Two
//! pairs share a period and a retention and leave together, the dependent first, because its
//! rows reference the other's ([`Partitioned::archived_with`]). Each table has a gate
//! ([`Gate`]) that keeps live rows in the database: a leaf failing its gate stays online as
//! retention debt and is never forced out.

use std::time::Duration;

use jiff::ToSpan as _;
use uuid::Uuid;

use crate::domain::time::{Date, Timestamp};

/// How far behind now the rollup counts: twice the longest `transaction_timeout` (60 s) of any
/// role that writes increments, so no increment can still commit below a consumed watermark.
pub const ROLLUP_LAG: Duration = Duration::from_secs(120);

/// How many finished days one recount run catches up at most. Increments live two days online,
/// so older days cannot be recounted from them anyway; the bound keeps a long outage from
/// turning one run into weeks of work.
pub const RECOUNT_CATCH_UP: i16 = 7;

/// The longest span `GET /analytics` reads at once, in days (both ends included).
pub const RANGE_MAX_DAYS: i32 = 366;

/// The smallest UUIDv7 that can be generated at `at`: its unix milliseconds in the top 48 bits,
/// the version and variant bits, and zeros (RFC 9562, <https://www.rfc-editor.org/rfc/rfc9562>).
/// The same value as the database's `uuidv7_boundary(at)`, so a cutoff computed here matches
/// the partition bounds and the rollup's watermark.
#[must_use]
pub fn uuidv7_boundary(at: Timestamp) -> Uuid {
    let millis = u128::try_from(at.0.as_millisecond()).unwrap_or(0) & 0xFFFF_FFFF_FFFF;
    Uuid::from_u128((millis << 80) | (0x7000_u128 << 64) | (0x8000_u128 << 48))
}

/// The instant a UUIDv7 was generated at (its top 48 bits, unix milliseconds): for a boundary,
/// the instant it bounds. `None` when the bits are out of range.
#[must_use]
pub fn uuidv7_instant(id: Uuid) -> Option<Timestamp> {
    let millis = i64::try_from(id.as_u128() >> 80).ok()?;
    jiff::Timestamp::from_millisecond(millis)
        .ok()
        .map(Timestamp)
}

/// The ids the rollup counts next: from the watermark (included) to the cutoff (excluded), or
/// nothing when the cutoff is not past the watermark. The watermark never moves backward, so a
/// run whose clock reads earlier than the last one counts nothing twice.
#[must_use]
pub fn drain_range(processed_to: Uuid, cutoff: Uuid) -> Option<(Uuid, Uuid)> {
    (cutoff > processed_to).then_some((processed_to, cutoff))
}

/// The days a recount run at `now` reconciles, oldest first: every finished UTC day after the
/// last recounted one, at most [`RECOUNT_CATCH_UP`] of them, ending with yesterday. With no
/// earlier recount, only yesterday.
#[must_use]
pub fn recount_days(last: Option<Date>, now: Timestamp) -> Vec<Date> {
    let today = Date::utc_day(now).0;
    let Ok(yesterday) = today.checked_sub(1.day()) else {
        return Vec::new();
    };
    let earliest = today
        .checked_sub(RECOUNT_CATCH_UP.days())
        .unwrap_or(yesterday);
    let mut day = match last.and_then(|last| last.0.checked_add(1.day()).ok()) {
        Some(next) => next.max(earliest),
        None => yesterday,
    };
    let mut days = Vec::new();
    while day <= yesterday {
        days.push(Date(day));
        match day.checked_add(1.day()) {
            Ok(next) => day = next,
            Err(_) => break,
        }
    }
    days
}

/// Whether the increments of a leaf covering `[lower, upper)` have all been counted and
/// reconciled, so the leaf may be dropped: the rollup's watermark is at or past the leaf's
/// upper bound, and the recount has recorded the last day the leaf covers (an increment is
/// written on or after its fact's day, so a leaf holds no day later than its own last one).
#[must_use]
pub fn increments_counted(upper: Timestamp, watermark: Uuid, recounted: Option<Date>) -> bool {
    let last_day = Date::utc_day(upper.minus(Duration::from_micros(1)));
    watermark >= uuidv7_boundary(upper) && recounted.is_some_and(|day| day >= last_day)
}

/// A table partitioned by period, as named in `partition_policies`.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    strum::EnumIter,
    strum::EnumString,
    strum::IntoStaticStr,
)]
#[strum(serialize_all = "snake_case")]
pub enum Partitioned {
    Messages,
    Attempts,
    DeliveryEvents,
    MessageEngagement,
    WebhookReceipts,
    OutboxEvents,
    WebhookDeliveries,
    StatsIncrements,
    MessageIdDirectory,
    TrackingEvents,
}

/// What must hold before a leaf may leave the database.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Gate {
    /// No message of the period is still queued, and none has an unsettled attempt.
    NothingInFlight,
    /// No provider receipt of the period still waits for normalisation.
    ReceiptsNormalized,
    /// The rollup counted the period and the recount reconciled its days
    /// ([`increments_counted`]).
    IncrementsCounted,
    /// Every outbox event of the period was published.
    OutboxPublished,
    /// No webhook delivery of the period is still pending.
    DeliveriesSettled,
    /// Nothing to wait for: the rows are history only.
    None,
}

impl Partitioned {
    /// The table's name.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        self.into()
    }

    /// For a dependent table, the table its leaves leave with: its rows reference that table's
    /// rows of the same period (an attempt its message, a delivery its event), so the dependent
    /// leaf is detached first, and both share one period and retention.
    #[must_use]
    pub fn archived_with(self) -> Option<Self> {
        match self {
            Self::Attempts => Some(Self::Messages),
            Self::WebhookDeliveries => Some(Self::OutboxEvents),
            _ => None,
        }
    }

    /// The dependent table that leaves before this one, if any.
    #[must_use]
    pub fn dependent(self) -> Option<Self> {
        match self {
            Self::Messages => Some(Self::Attempts),
            Self::OutboxEvents => Some(Self::WebhookDeliveries),
            _ => None,
        }
    }

    /// The table's gate.
    #[must_use]
    pub fn gate(self) -> Gate {
        match self {
            Self::Messages => Gate::NothingInFlight,
            Self::WebhookReceipts => Gate::ReceiptsNormalized,
            Self::StatsIncrements => Gate::IncrementsCounted,
            Self::OutboxEvents => Gate::OutboxPublished,
            Self::WebhookDeliveries => Gate::DeliveriesSettled,
            // An attempt leaves with its message, under the message's gate; the tracker's spool
            // is on another host, and a late drain into a dropped month fails visibly while the
            // spool keeps its rows.
            Self::Attempts
            | Self::DeliveryEvents
            | Self::MessageEngagement
            | Self::MessageIdDirectory
            | Self::TrackingEvents => Gate::None,
        }
    }

    /// The column holding the workspace a leaf's row belongs to (every partitioned table has
    /// one), and the column whose instant orders it: its partition key.
    #[must_use]
    pub fn key(self) -> &'static str {
        match self {
            Self::Attempts | Self::MessageEngagement => "message_id",
            Self::WebhookDeliveries => "event_id",
            Self::TrackingEvents => "occurred_at",
            Self::Messages
            | Self::DeliveryEvents
            | Self::WebhookReceipts
            | Self::OutboxEvents
            | Self::StatsIncrements
            | Self::MessageIdDirectory => "id",
        }
    }
}

/// How `GET /analytics` groups its counters.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    strum::EnumIter,
    strum::IntoStaticStr,
    utoipa::ToSchema,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum GroupBy {
    /// One row per UTC day.
    Day,
    /// One row per campaign.
    Campaign,
    /// One row per step of a campaign.
    Step,
    /// One row per variant (and version) of a step.
    Variant,
}

/// Why an analytics range is refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum RangeError {
    /// `from` is after `to`.
    #[error("`from` must not be after `to`")]
    Reversed,
    /// The span is longer than [`RANGE_MAX_DAYS`].
    #[error("the range covers at most 366 days")]
    TooLong,
}

/// The days an analytics query covers, both ends included: by default the 30 days ending
/// today (UTC); a missing end is filled from the other one. Refused when reversed or longer
/// than [`RANGE_MAX_DAYS`].
///
/// # Errors
///
/// [`RangeError`].
pub fn range(
    from: Option<Date>,
    to: Option<Date>,
    now: Timestamp,
) -> Result<(Date, Date), RangeError> {
    let today = Date::utc_day(now).0;
    let to = to.map_or(today, |to| to.0);
    let from = match from {
        Some(from) => from.0,
        None => to.checked_sub(29.days()).unwrap_or(to),
    };
    if from > to {
        return Err(RangeError::Reversed);
    }
    let span = to.since(from).map_or(i32::MAX, |span| span.get_days());
    if span >= RANGE_MAX_DAYS {
        return Err(RangeError::TooLong);
    }
    Ok((Date(from), Date(to)))
}

/// An event count per 10,000 accepted messages. Zero sends means no rate. Integer arithmetic
/// rounds toward zero and avoids floating-point NaN/Infinity on the public wire.
#[must_use]
pub fn rate_per_10000(events: i64, sent: i64) -> Option<i64> {
    (sent > 0).then(|| {
        i64::try_from(i128::from(events).saturating_mul(10_000) / i128::from(sent))
            .unwrap_or(i64::MAX)
    })
}

#[cfg(test)]
mod tests {
    /// Empty denominators produce null and ordinary ratios use deterministic basis points.
    #[test]
    fn rates_are_bounded_integer_arithmetic() {
        assert_eq!(rate_per_10000(3, 0), None);
        assert_eq!(rate_per_10000(1, 3), Some(3333));
        assert_eq!(rate_per_10000(0, 3), Some(0));
        assert_eq!(rate_per_10000(i64::MAX, 1), Some(i64::MAX));
    }

    use std::str::FromStr as _;

    use jiff::civil::date;
    use strum::IntoEnumIterator as _;
    use uuid::Uuid;

    use super::*;

    fn at(text: &str) -> Timestamp {
        Timestamp(text.parse().expect("an instant"))
    }

    /// The boundary of an instant is the smallest UUIDv7 of its millisecond, with the version
    /// and variant bits set, and the order of boundaries is the order of instants: partition
    /// bounds and the rollup's cutoff are compared as uuids, so the mapping must be exact and
    /// monotonic, and agree with the database's `uuidv7_boundary`.
    #[test]
    fn boundary_is_the_smallest_uuidv7_of_its_millisecond() {
        let boundary = uuidv7_boundary(at("2026-10-01T00:00:00Z"));
        assert_eq!(boundary.to_string(), "01a0f4c2-c400-7000-8000-000000000000");
        assert_eq!(boundary.get_version_num(), 7);
        assert_eq!(uuidv7_instant(boundary), Some(at("2026-10-01T00:00:00Z")));
        let later = uuidv7_boundary(at("2026-10-01T00:00:00.001Z"));
        assert!(later > boundary);
        let last = Uuid::parse_str("01a0f4c2-c400-7fff-bfff-ffffffffffff")
            .expect("the largest UUIDv7 in the same millisecond");
        assert!(boundary < last && last < later);
    }

    /// The rollup's range is the watermark up to the cutoff, and nothing when the cutoff is not
    /// past the watermark: a clock that steps back never recounts ids already counted.
    #[test]
    fn the_watermark_only_moves_forward() {
        let earlier = uuidv7_boundary(at("2026-10-01T00:00:00Z"));
        let later = uuidv7_boundary(at("2026-10-01T00:05:00Z"));
        assert_eq!(drain_range(earlier, later), Some((earlier, later)));
        assert_eq!(drain_range(later, later), None);
        assert_eq!(drain_range(later, earlier), None);
    }

    /// The recount owns every finished day after the last one it recorded, at most a week of
    /// them, and only yesterday when it never ran; a day already recounted (or today) is never
    /// in the list, so a second run the same night does nothing.
    #[test]
    fn recount_days_catch_up_missed_nights_within_a_bound() {
        let now = at("2026-10-10T00:45:00Z");
        let day = |d| Date(date(2026, 10, d));
        assert_eq!(recount_days(None, now), vec![day(9)]);
        assert_eq!(recount_days(Some(day(8)), now), vec![day(9)]);
        assert_eq!(
            recount_days(Some(day(6)), now),
            vec![day(7), day(8), day(9)]
        );
        assert_eq!(recount_days(Some(day(9)), now), Vec::<Date>::new());
        assert_eq!(recount_days(Some(day(10)), now), Vec::<Date>::new());
        let long_ago = recount_days(Some(Date(date(2026, 1, 1))), now);
        assert_eq!(
            long_ago.len(),
            usize::try_from(RECOUNT_CATCH_UP).unwrap_or(0)
        );
        assert_eq!(long_ago.first(), Some(&day(3)));
        assert_eq!(long_ago.last(), Some(&day(9)));
    }

    /// An increments leaf may go only once the watermark reached its upper bound and the
    /// recount recorded its last day (the day itself for a daily leaf, the month's last day for
    /// a monthly one): otherwise rows still uncounted, or a day not yet reconciled, would be
    /// dropped.
    #[test]
    fn an_increments_leaf_waits_for_the_rollup_and_the_recount() {
        let upper = at("2026-10-02T00:00:00Z");
        let past = uuidv7_boundary(upper);
        let short = uuidv7_boundary(at("2026-10-01T23:59:59Z"));
        let first = Some(Date(date(2026, 10, 1)));
        let before = Some(Date(date(2026, 9, 30)));
        assert!(increments_counted(upper, past, first));
        assert!(!increments_counted(upper, short, first));
        assert!(!increments_counted(upper, past, before));
        assert!(!increments_counted(upper, past, None));
        let month_end = at("2026-11-01T00:00:00Z");
        assert!(!increments_counted(
            month_end,
            uuidv7_boundary(month_end),
            first
        ));
        assert!(increments_counted(
            month_end,
            uuidv7_boundary(month_end),
            Some(Date(date(2026, 10, 31)))
        ));
    }

    /// Every partitioned table has a gate and a key, parses from its own name, and the archive
    /// pairs are symmetric: the dependent leaves with exactly the table that names it as its
    /// dependent, and a dependent never has a dependent of its own (the order is two levels).
    #[test]
    fn every_partitioned_table_has_a_gate_and_symmetric_pairs() {
        for table in Partitioned::iter() {
            assert_eq!(Partitioned::from_str(table.as_str()), Ok(table));
            let expected = match table {
                Partitioned::Messages => Gate::NothingInFlight,
                Partitioned::WebhookReceipts => Gate::ReceiptsNormalized,
                Partitioned::StatsIncrements => Gate::IncrementsCounted,
                Partitioned::OutboxEvents => Gate::OutboxPublished,
                Partitioned::WebhookDeliveries => Gate::DeliveriesSettled,
                Partitioned::Attempts
                | Partitioned::DeliveryEvents
                | Partitioned::MessageEngagement
                | Partitioned::MessageIdDirectory
                | Partitioned::TrackingEvents => Gate::None,
            };
            assert_eq!(table.gate(), expected, "{table:?}");
            assert!(!table.key().is_empty());
            if let Some(parent) = table.archived_with() {
                assert_eq!(parent.dependent(), Some(table));
                assert_eq!(table.dependent(), None);
            }
            if let Some(dependent) = table.dependent() {
                assert_eq!(dependent.archived_with(), Some(table));
            }
        }
    }

    /// A range defaults to the 30 days ending today, fills a missing end from the other, and is
    /// refused when reversed or longer than 366 days: the counters are read per day, and an
    /// unbounded range would read a workspace's whole history on one request.
    #[test]
    fn analytics_ranges_are_bounded() {
        let now = at("2026-10-10T12:00:00Z");
        let day = |y, m, d| Date(date(y, m, d));
        assert_eq!(
            range(None, None, now),
            Ok((day(2026, 9, 11), day(2026, 10, 10)))
        );
        assert_eq!(
            range(None, Some(day(2026, 9, 30)), now),
            Ok((day(2026, 9, 1), day(2026, 9, 30)))
        );
        assert_eq!(
            range(Some(day(2026, 10, 2)), Some(day(2026, 10, 1)), now),
            Err(RangeError::Reversed)
        );
        assert_eq!(
            range(Some(day(2025, 10, 9)), Some(day(2026, 10, 9)), now),
            Ok((day(2025, 10, 9), day(2026, 10, 9)))
        );
        assert_eq!(
            range(Some(day(2025, 10, 8)), Some(day(2026, 10, 9)), now),
            Err(RangeError::TooLong)
        );
        for group in GroupBy::iter() {
            assert!(!<&str>::from(group).is_empty());
        }
    }
}
